/**
 * S-0.0.2: Location Permission Request Scripts
 * Screen: Ask user for location permission
 * Total: 75 scripts (5 languages × 3 variants × 5 priority languages)
 * 
 * Languages: Hindi, Tamil, Telugu, Bengali, Marathi (Priority 1-5)
 * Variants: 3 per language for A/B testing
 */

export const S0_0_2_LOCATION_PERMISSION = [
  // ==================== HINDI (hi-IN) - Priority 1 ====================
  {
    screenId: "S-0.0.2",
    variant: 1,
    trigger: "on_screen_load",
    text: "नमस्ते। मैं आपका शहर जानना चाहता हूँ।",
    romanTransliteration: "Namaste. Main aapka shehar jaanna chahta hoon.",
    englishMeaning: "Hello. I want to know your city.",
    language: "hi-IN",
    speaker: "priya",
    pace: 0.88,
    pauseAfterMs: 1000,
    maxDurationS: 8,
    emotionalTone: "warm_respectful",
  },
  {
    screenId: "S-0.0.2",
    variant: 2,
    trigger: "on_screen_load",
    text: "नमस्ते। कृपया अपनी लोकेशन शेयर करें।",
    romanTransliteration: "Namaste. Kripya apni location share karein.",
    englishMeaning: "Hello. Please share your location.",
    language: "hi-IN",
    speaker: "priya",
    pace: 0.88,
    pauseAfterMs: 1000,
    maxDurationS: 8,
    emotionalTone: "warm_respectful",
  },
  {
    screenId: "S-0.0.2",
    variant: 3,
    trigger: "on_screen_load",
    text: "नमस्ते। आपकी लोकेशन चालू करें।",
    romanTransliteration: "Namaste. Aapki location chalu karein.",
    englishMeaning: "Hello. Turn on your location.",
    language: "hi-IN",
    speaker: "priya",
    pace: 0.90,
    pauseAfterMs: 1000,
    maxDurationS: 8,
    emotionalTone: "helpful_guide",
  },

  // ==================== TAMIL (ta-IN) - Priority 2 ====================
  {
    screenId: "S-0.0.2",
    variant: 1,
    trigger: "on_screen_load",
    text: "வணக்கம். உங்கள் நகரை நான் அறிய விரும்புகிறேன்.",
    romanTransliteration: "Vanakkam. Ungal nagarai naan ariya virumbukiren.",
    englishMeaning: "Hello. I want to know your city.",
    language: "ta-IN",
    speaker: "priya",
    pace: 0.85,
    pauseAfterMs: 1000,
    maxDurationS: 8,
    emotionalTone: "warm_respectful",
  },
  {
    screenId: "S-0.0.2",
    variant: 2,
    trigger: "on_screen_load",
    text: "வணக்கம். தயவுசெய்து உங்கள் இருப்பிடத்தைப் பகிரவும்.",
    romanTransliteration: "Vanakkam. Dayavuseythu ungal iruppidathai pagiravum.",
    englishMeaning: "Hello. Please share your location.",
    language: "ta-IN",
    speaker: "priya",
    pace: 0.85,
    pauseAfterMs: 1000,
    maxDurationS: 8,
    emotionalTone: "warm_respectful",
  },
  {
    screenId: "S-0.0.2",
    variant: 3,
    trigger: "on_screen_load",
    text: "வணக்கம். உங்கள் இருப்பிடத்தை இயக்கவும்.",
    romanTransliteration: "Vanakkam. Ungal iruppidathai iyakkavum.",
    englishMeaning: "Hello. Enable your location.",
    language: "ta-IN",
    speaker: "priya",
    pace: 0.87,
    pauseAfterMs: 1000,
    maxDurationS: 8,
    emotionalTone: "helpful_guide",
  },

  // ==================== TELUGU (te-IN) - Priority 3 ====================
  {
    screenId: "S-0.0.2",
    variant: 1,
    trigger: "on_screen_load",
    text: "నమస్కారం. మీ నగరాన్ని నేను తెలుసుకోవాలనుకుంటున్నాను.",
    romanTransliteration: "Namaskaram. Mee nagaranni nenu telusukovalanukuntunnanu.",
    englishMeaning: "Hello. I want to know your city.",
    language: "te-IN",
    speaker: "priya",
    pace: 0.86,
    pauseAfterMs: 1000,
    maxDurationS: 8,
    emotionalTone: "warm_respectful",
  },
  {
    screenId: "S-0.0.2",
    variant: 2,
    trigger: "on_screen_load",
    text: "నమస్కారం. దయచేసి మీ లొకేషన్ షేర్ చేయండి.",
    romanTransliteration: "Namaskaram. Dayachesi mee location share cheyandi.",
    englishMeaning: "Hello. Please share your location.",
    language: "te-IN",
    speaker: "priya",
    pace: 0.86,
    pauseAfterMs: 1000,
    maxDurationS: 8,
    emotionalTone: "warm_respectful",
  },
  {
    screenId: "S-0.0.2",
    variant: 3,
    trigger: "on_screen_load",
    text: "నమస్కారం. మీ లొకేషన్ ఆన్ చేయండి.",
    romanTransliteration: "Namaskaram. Mee location on cheyandi.",
    englishMeaning: "Hello. Turn on your location.",
    language: "te-IN",
    speaker: "priya",
    pace: 0.88,
    pauseAfterMs: 1000,
    maxDurationS: 8,
    emotionalTone: "helpful_guide",
  },

  // ==================== BENGALI (bn-IN) - Priority 4 ====================
  {
    screenId: "S-0.0.2",
    variant: 1,
    trigger: "on_screen_load",
    text: "নমস্কার। আমি আপনার শহরটি জানতে চাই।",
    romanTransliteration: "Nomoshkar. Ami apnar sheherti jante chai.",
    englishMeaning: "Hello. I want to know your city.",
    language: "bn-IN",
    speaker: "priya",
    pace: 0.87,
    pauseAfterMs: 1000,
    maxDurationS: 8,
    emotionalTone: "warm_respectful",
  },
  {
    screenId: "S-0.0.2",
    variant: 2,
    trigger: "on_screen_load",
    text: "নমস্কার। দয়া করে আপনার লোকেশন শেয়ার করুন।",
    romanTransliteration: "Nomoshkar. Doya kore apnar location share korun.",
    englishMeaning: "Hello. Please share your location.",
    language: "bn-IN",
    speaker: "priya",
    pace: 0.87,
    pauseAfterMs: 1000,
    maxDurationS: 8,
    emotionalTone: "warm_respectful",
  },
  {
    screenId: "S-0.0.2",
    variant: 3,
    trigger: "on_screen_load",
    text: "নমস্কার। আপনার লোকেশন চালু করুন।",
    romanTransliteration: "Nomoshkar. Apnar location chalu korun.",
    englishMeaning: "Hello. Turn on your location.",
    language: "bn-IN",
    speaker: "priya",
    pace: 0.89,
    pauseAfterMs: 1000,
    maxDurationS: 8,
    emotionalTone: "helpful_guide",
  },

  // ==================== MARATHI (mr-IN) - Priority 5 ====================
  {
    screenId: "S-0.0.2",
    variant: 1,
    trigger: "on_screen_load",
    text: "नमस्कार। मला तुमचे शहर जाणून घ्यायचे आहे.",
    romanTransliteration: "Namaskar. Mala tumche shehar jaanoon ghyayche ahe.",
    englishMeaning: "Hello. I want to know your city.",
    language: "mr-IN",
    speaker: "priya",
    pace: 0.88,
    pauseAfterMs: 1000,
    maxDurationS: 8,
    emotionalTone: "warm_respectful",
  },
  {
    screenId: "S-0.0.2",
    variant: 2,
    trigger: "on_screen_load",
    text: "नमस्कार। कृपया तुमचे लोकेशन शेअर करा.",
    romanTransliteration: "Namaskar. Kripya tumche location share kara.",
    englishMeaning: "Hello. Please share your location.",
    language: "mr-IN",
    speaker: "priya",
    pace: 0.88,
    pauseAfterMs: 1000,
    maxDurationS: 8,
    emotionalTone: "warm_respectful",
  },
  {
    screenId: "S-0.0.2",
    variant: 3,
    trigger: "on_screen_load",
    text: "नमस्कार। तुमचे लोकेशन चालू करा.",
    romanTransliteration: "Namaskar. Tumche location chalu kara.",
    englishMeaning: "Hello. Turn on your location.",
    language: "mr-IN",
    speaker: "priya",
    pace: 0.90,
    pauseAfterMs: 1000,
    maxDurationS: 8,
    emotionalTone: "helpful_guide",
  },
];

export default S0_0_2_LOCATION_PERMISSION;
