/**
 * S-0.0.2B: Manual City Entry Scripts
 * Screen: User manually types their city name
 * Total: 30 scripts (15 languages × 2 variants)
 * 
 * Includes dynamic [CITY_NAME] variable support
 */

export const S0_0_2B_MANUAL_CITY = [
  // ==================== HINDI (hi-IN) ====================
  {
    screenId: "S-0.0.2B",
    variant: 1,
    trigger: "on_screen_load",
    text: "कृपया अपना शहर टाइप करें।",
    romanTransliteration: "Kripya apna shehar type karein.",
    englishMeaning: "Please type your city.",
    language: "hi-IN",
    speaker: "priya",
    pace: 0.88,
    pauseAfterMs: 900,
    maxDurationS: 7,
    emotionalTone: "helpful_guide",
    dynamicVariables: {
      placeholder: "[CITY_NAME] टाइप करें",
    },
  },
  {
    screenId: "S-0.0.2B",
    variant: 2,
    trigger: "on_screen_load",
    text: "यहाँ अपने शहर का नाम लिखें।",
    romanTransliteration: "Yahan apne shehar ka naam likhein.",
    englishMeaning: "Write your city name here.",
    language: "hi-IN",
    speaker: "priya",
    pace: 0.88,
    pauseAfterMs: 900,
    maxDurationS: 7,
    emotionalTone: "helpful_guide",
    dynamicVariables: {
      placeholder: "[CITY_NAME] लिखें",
    },
  },

  // ==================== TAMIL (ta-IN) ====================
  {
    screenId: "S-0.0.2B",
    variant: 1,
    trigger: "on_screen_load",
    text: "தயவுசெய்து உங்கள் நகரை டைப் செய்யவும்.",
    romanTransliteration: "Dayavuseythu ungal nagarai type seyyavum.",
    englishMeaning: "Please type your city.",
    language: "ta-IN",
    speaker: "priya",
    pace: 0.86,
    pauseAfterMs: 900,
    maxDurationS: 7,
    emotionalTone: "helpful_guide",
    dynamicVariables: {
      placeholder: "[CITY_NAME] டைப் செய்யவும்",
    },
  },
  {
    screenId: "S-0.0.2B",
    variant: 2,
    trigger: "on_screen_load",
    text: "இங்கே உங்கள் நகரத்தின் பெயரை எழுதவும்.",
    romanTransliteration: "Inge ungal nagarathin peyarai ezhuthavum.",
    englishMeaning: "Write your city name here.",
    language: "ta-IN",
    speaker: "priya",
    pace: 0.86,
    pauseAfterMs: 900,
    maxDurationS: 7,
    emotionalTone: "helpful_guide",
    dynamicVariables: {
      placeholder: "[CITY_NAME] எழுதவும்",
    },
  },

  // ==================== TELUGU (te-IN) ====================
  {
    screenId: "S-0.0.2B",
    variant: 1,
    trigger: "on_screen_load",
    text: "దయచేసి మీ నగరాన్ని టైప్ చేయండి.",
    romanTransliteration: "Dayachesi mee nagaranni type cheyandi.",
    englishMeaning: "Please type your city.",
    language: "te-IN",
    speaker: "priya",
    pace: 0.87,
    pauseAfterMs: 900,
    maxDurationS: 7,
    emotionalTone: "helpful_guide",
    dynamicVariables: {
      placeholder: "[CITY_NAME] టైప్ చేయండి",
    },
  },
  {
    screenId: "S-0.0.2B",
    variant: 2,
    trigger: "on_screen_load",
    text: "ఇక్కడ మీ నగరం పేరు రాయండి.",
    romanTransliteration: "Ikkada mee nagaram peru rayandi.",
    englishMeaning: "Write your city name here.",
    language: "te-IN",
    speaker: "priya",
    pace: 0.87,
    pauseAfterMs: 900,
    maxDurationS: 7,
    emotionalTone: "helpful_guide",
    dynamicVariables: {
      placeholder: "[CITY_NAME] రాయండి",
    },
  },

  // ==================== BENGALI (bn-IN) ====================
  {
    screenId: "S-0.0.2B",
    variant: 1,
    trigger: "on_screen_load",
    text: "দয়া করে আপনার শহর টাইপ করুন।",
    romanTransliteration: "Doya kore apnar shehar type korun.",
    englishMeaning: "Please type your city.",
    language: "bn-IN",
    speaker: "priya",
    pace: 0.88,
    pauseAfterMs: 900,
    maxDurationS: 7,
    emotionalTone: "helpful_guide",
    dynamicVariables: {
      placeholder: "[CITY_NAME] টাইপ করুন",
    },
  },
  {
    screenId: "S-0.0.2B",
    variant: 2,
    trigger: "on_screen_load",
    text: "এখানে আপনার শহরের নাম লিখুন।",
    romanTransliteration: "Ekhane apnar shehorer naam likhun.",
    englishMeaning: "Write your city name here.",
    language: "bn-IN",
    speaker: "priya",
    pace: 0.88,
    pauseAfterMs: 900,
    maxDurationS: 7,
    emotionalTone: "helpful_guide",
    dynamicVariables: {
      placeholder: "[CITY_NAME] লিখুন",
    },
  },

  // ==================== MARATHI (mr-IN) ====================
  {
    screenId: "S-0.0.2B",
    variant: 1,
    trigger: "on_screen_load",
    text: "कृपया तुमचे शहर टाइप करा.",
    romanTransliteration: "Kripya tumche shehar type kara.",
    englishMeaning: "Please type your city.",
    language: "mr-IN",
    speaker: "priya",
    pace: 0.89,
    pauseAfterMs: 900,
    maxDurationS: 7,
    emotionalTone: "helpful_guide",
    dynamicVariables: {
      placeholder: "[CITY_NAME] टाइप करा",
    },
  },
  {
    screenId: "S-0.0.2B",
    variant: 2,
    trigger: "on_screen_load",
    text: "येथे तुमच्या शहराचे नाव लिहा.",
    romanTransliteration: "Yethe tumchya sheharache naav liha.",
    englishMeaning: "Write your city name here.",
    language: "mr-IN",
    speaker: "priya",
    pace: 0.89,
    pauseAfterMs: 900,
    maxDurationS: 7,
    emotionalTone: "helpful_guide",
    dynamicVariables: {
      placeholder: "[CITY_NAME] लिहा",
    },
  },

  // ==================== GUJARATI (gu-IN) ====================
  {
    screenId: "S-0.0.2B",
    variant: 1,
    trigger: "on_screen_load",
    text: "કૃપા કરીને તમારા શહેરનું નામ ટાઇપ કરો.",
    romanTransliteration: "Kripa karine tamara shehernu naam type karo.",
    englishMeaning: "Please type your city.",
    language: "gu-IN",
    speaker: "priya",
    pace: 0.88,
    pauseAfterMs: 900,
    maxDurationS: 7,
    emotionalTone: "helpful_guide",
    dynamicVariables: {
      placeholder: "[CITY_NAME] ટાઇપ કરો",
    },
  },
  {
    screenId: "S-0.0.2B",
    variant: 2,
    trigger: "on_screen_load",
    text: "અહીં તમારા શહેરનું નામ લખો.",
    romanTransliteration: "Ahi tamara shehernu naam lakho.",
    englishMeaning: "Write your city name here.",
    language: "gu-IN",
    speaker: "priya",
    pace: 0.88,
    pauseAfterMs: 900,
    maxDurationS: 7,
    emotionalTone: "helpful_guide",
    dynamicVariables: {
      placeholder: "[CITY_NAME] લખો",
    },
  },

  // ==================== KANNADA (kn-IN) ====================
  {
    screenId: "S-0.0.2B",
    variant: 1,
    trigger: "on_screen_load",
    text: "ದಯವಿಟ್ಟು ನಿಮ್ಮ ನಗರವನ್ನು ಟೈಪ್ ಮಾಡಿ.",
    romanTransliteration: "Dayavittu nimma nagaravannu type maadi.",
    englishMeaning: "Please type your city.",
    language: "kn-IN",
    speaker: "priya",
    pace: 0.87,
    pauseAfterMs: 900,
    maxDurationS: 7,
    emotionalTone: "helpful_guide",
    dynamicVariables: {
      placeholder: "[CITY_NAME] ಟೈಪ್ ಮಾಡಿ",
    },
  },
  {
    screenId: "S-0.0.2B",
    variant: 2,
    trigger: "on_screen_load",
    text: "ಇಲ್ಲಿ ನಿಮ್ಮ ನಗರದ ಹೆಸರನ್ನು ಬರೆಯಿರಿ.",
    romanTransliteration: "Illi nimma nagarada hesarannu bareyiri.",
    englishMeaning: "Write your city name here.",
    language: "kn-IN",
    speaker: "priya",
    pace: 0.87,
    pauseAfterMs: 900,
    maxDurationS: 7,
    emotionalTone: "helpful_guide",
    dynamicVariables: {
      placeholder: "[CITY_NAME] ಬರೆಯಿರಿ",
    },
  },

  // ==================== MALAYALAM (ml-IN) ====================
  {
    screenId: "S-0.0.2B",
    variant: 1,
    trigger: "on_screen_load",
    text: "ദയവായി നിങ്ങളുടെ നഗരം ടൈപ്പ് ചെയ്യുക.",
    romanTransliteration: "Dayavayi ningalude nagaram type cheyyuka.",
    englishMeaning: "Please type your city.",
    language: "ml-IN",
    speaker: "priya",
    pace: 0.86,
    pauseAfterMs: 900,
    maxDurationS: 7,
    emotionalTone: "helpful_guide",
    dynamicVariables: {
      placeholder: "[CITY_NAME] ടൈപ്പ് ചെയ്യുക",
    },
  },
  {
    screenId: "S-0.0.2B",
    variant: 2,
    trigger: "on_screen_load",
    text: "ഇവിടെ നിങ്ങളുടെ നഗരത്തിന്റെ പേര് എഴുതുക.",
    romanTransliteration: "Ivide ningalude nagarathinte peru ezhuthuka.",
    englishMeaning: "Write your city name here.",
    language: "ml-IN",
    speaker: "priya",
    pace: 0.86,
    pauseAfterMs: 900,
    maxDurationS: 7,
    emotionalTone: "helpful_guide",
    dynamicVariables: {
      placeholder: "[CITY_NAME] എഴുതുക",
    },
  },

  // ==================== PUNJABI (pa-IN) ====================
  {
    screenId: "S-0.0.2B",
    variant: 1,
    trigger: "on_screen_load",
    text: "ਕਿਰਪਾ ਕਰਕੇ ਆਪਣਾ ਸ਼ਹਿਰ ਟਾਈਪ ਕਰੋ।",
    romanTransliteration: "Kirpa karke apna shehar type karo.",
    englishMeaning: "Please type your city.",
    language: "pa-IN",
    speaker: "priya",
    pace: 0.88,
    pauseAfterMs: 900,
    maxDurationS: 7,
    emotionalTone: "helpful_guide",
    dynamicVariables: {
      placeholder: "[CITY_NAME] ਟਾਈਪ ਕਰੋ",
    },
  },
  {
    screenId: "S-0.0.2B",
    variant: 2,
    trigger: "on_screen_load",
    text: "ਇੱਥੇ ਆਪਣੇ ਸ਼ਹਿਰ ਦਾ ਨਾਮ ਲਿਖੋ।",
    romanTransliteration: "Itthe apne shehar da naam likho.",
    englishMeaning: "Write your city name here.",
    language: "pa-IN",
    speaker: "priya",
    pace: 0.88,
    pauseAfterMs: 900,
    maxDurationS: 7,
    emotionalTone: "helpful_guide",
    dynamicVariables: {
      placeholder: "[CITY_NAME] ਲਿਖੋ",
    },
  },

  // ==================== ODIA (or-IN) ====================
  {
    screenId: "S-0.0.2B",
    variant: 1,
    trigger: "on_screen_load",
    text: "ଦୟାକରି ଆପଣଙ୍କ ସହର ଟାଇପ୍ କରନ୍ତୁ।",
    romanTransliteration: "Dayakari aapanka sahara type karantu.",
    englishMeaning: "Please type your city.",
    language: "or-IN",
    speaker: "priya",
    pace: 0.87,
    pauseAfterMs: 900,
    maxDurationS: 7,
    emotionalTone: "helpful_guide",
    dynamicVariables: {
      placeholder: "[CITY_NAME] ଟାଇପ୍ କରନ୍ତୁ",
    },
  },
  {
    screenId: "S-0.0.2B",
    variant: 2,
    trigger: "on_screen_load",
    text: "ଏଠାରେ ଆପଣଙ୍କ ସହରର ନାମ ଲେଖନ୍ତୁ।",
    romanTransliteration: "Ethare aapanka saharara nama lekhantu.",
    englishMeaning: "Write your city name here.",
    language: "or-IN",
    speaker: "priya",
    pace: 0.87,
    pauseAfterMs: 900,
    maxDurationS: 7,
    emotionalTone: "helpful_guide",
    dynamicVariables: {
      placeholder: "[CITY_NAME] ଲେଖନ୍ତୁ",
    },
  },

  // ==================== ENGLISH (en-IN) ====================
  {
    screenId: "S-0.0.2B",
    variant: 1,
    trigger: "on_screen_load",
    text: "Please type your city.",
    romanTransliteration: "Please type your city.",
    englishMeaning: "Please type your city.",
    language: "en-IN",
    speaker: "priya",
    pace: 0.90,
    pauseAfterMs: 900,
    maxDurationS: 7,
    emotionalTone: "helpful_guide",
    dynamicVariables: {
      placeholder: "Type [CITY_NAME]",
    },
  },
  {
    screenId: "S-0.0.2B",
    variant: 2,
    trigger: "on_screen_load",
    text: "Write your city name here.",
    romanTransliteration: "Write your city name here.",
    englishMeaning: "Write your city name here.",
    language: "en-IN",
    speaker: "priya",
    pace: 0.90,
    pauseAfterMs: 900,
    maxDurationS: 7,
    emotionalTone: "helpful_guide",
    dynamicVariables: {
      placeholder: "Enter [CITY_NAME]",
    },
  },

  // ==================== BHOJPURI (hi-IN fallback) ====================
  {
    screenId: "S-0.0.2B",
    variant: 1,
    trigger: "on_screen_load",
    text: "कृपया अपना शहर टाइप करीं।",
    romanTransliteration: "Kripya apna shehar type kareen.",
    englishMeaning: "Please type your city.",
    language: "hi-IN",
    speaker: "priya",
    pace: 0.88,
    pauseAfterMs: 900,
    maxDurationS: 7,
    emotionalTone: "helpful_guide",
    fallback: true,
    dynamicVariables: {
      placeholder: "[CITY_NAME] टाइप करीं",
    },
  },
  {
    screenId: "S-0.0.2B",
    variant: 2,
    trigger: "on_screen_load",
    text: "इहाँ अपना शहर के नाम लिखीं।",
    romanTransliteration: "Yahan apna shehar ke naam likheen.",
    englishMeaning: "Write your city name here.",
    language: "hi-IN",
    speaker: "priya",
    pace: 0.88,
    pauseAfterMs: 900,
    maxDurationS: 7,
    emotionalTone: "helpful_guide",
    fallback: true,
    dynamicVariables: {
      placeholder: "[CITY_NAME] लिखीं",
    },
  },

  // ==================== MAITHILI (hi-IN fallback) ====================
  {
    screenId: "S-0.0.2B",
    variant: 1,
    trigger: "on_screen_load",
    text: "कृपया अपन शहर टाइप करू।",
    romanTransliteration: "Kripya apna shehar type karu.",
    englishMeaning: "Please type your city.",
    language: "hi-IN",
    speaker: "priya",
    pace: 0.88,
    pauseAfterMs: 900,
    maxDurationS: 7,
    emotionalTone: "helpful_guide",
    fallback: true,
    dynamicVariables: {
      placeholder: "[CITY_NAME] टाइप करू",
    },
  },
  {
    screenId: "S-0.0.2B",
    variant: 2,
    trigger: "on_screen_load",
    text: "एतए अपन शहरक नाम लिखू।",
    romanTransliteration: "Etay apna sheharak naam likhu.",
    englishMeaning: "Write your city name here.",
    language: "hi-IN",
    speaker: "priya",
    pace: 0.88,
    pauseAfterMs: 900,
    maxDurationS: 7,
    emotionalTone: "helpful_guide",
    fallback: true,
    dynamicVariables: {
      placeholder: "[CITY_NAME] लिखू",
    },
  },

  // ==================== SANSKRIT (hi-IN fallback) ====================
  {
    screenId: "S-0.0.2B",
    variant: 1,
    trigger: "on_screen_load",
    text: "कृपया स्वनगरं टाइपयतु।",
    romanTransliteration: "Kripya swanagaram typayatu.",
    englishMeaning: "Please type your city.",
    language: "hi-IN",
    speaker: "priya",
    pace: 0.85,
    pauseAfterMs: 900,
    maxDurationS: 7,
    emotionalTone: "warm_respectful",
    fallback: true,
    dynamicVariables: {
      placeholder: "[CITY_NAME] टाइपयतु",
    },
  },
  {
    screenId: "S-0.0.2B",
    variant: 2,
    trigger: "on_screen_load",
    text: "अत्र स्वनगरस्य नाम लिखतु।",
    romanTransliteration: "Atra swanagarasya naam likhatu.",
    englishMeaning: "Write your city name here.",
    language: "hi-IN",
    speaker: "priya",
    pace: 0.85,
    pauseAfterMs: 900,
    maxDurationS: 7,
    emotionalTone: "warm_respectful",
    fallback: true,
    dynamicVariables: {
      placeholder: "[CITY_NAME] लिखतु",
    },
  },

  // ==================== ASSAMESE (hi-IN fallback) ====================
  {
    screenId: "S-0.0.2B",
    variant: 1,
    trigger: "on_screen_load",
    text: "অনুগ্ৰহ কৰি আপোনাৰ চহৰ টাইপ কৰক।",
    romanTransliteration: "Anugraha kari apunar sahar type korok.",
    englishMeaning: "Please type your city.",
    language: "hi-IN",
    speaker: "priya",
    pace: 0.87,
    pauseAfterMs: 900,
    maxDurationS: 7,
    emotionalTone: "helpful_guide",
    fallback: true,
    dynamicVariables: {
      placeholder: "[CITY_NAME] টাইপ কৰক",
    },
  },
  {
    screenId: "S-0.0.2B",
    variant: 2,
    trigger: "on_screen_load",
    text: "ইয়াত আপোনাৰ চহৰৰ নাম লিখক।",
    romanTransliteration: "Yat apunar saharor naam likhok.",
    englishMeaning: "Write your city name here.",
    language: "hi-IN",
    speaker: "priya",
    pace: 0.87,
    pauseAfterMs: 900,
    maxDurationS: 7,
    emotionalTone: "helpful_guide",
    fallback: true,
    dynamicVariables: {
      placeholder: "[CITY_NAME] লিখক",
    },
  },
];

export default S0_0_2B_MANUAL_CITY;
