/**
 * S-0.0.3: City Selection Screen Scripts
 * Screen: User selects city from list
 * Total: 60 scripts (15 languages × 4 variants)
 */

export const S0_0_3_CITY_SELECTION = [
  // ==================== HINDI (hi-IN) ====================
  {
    screenId: "S-0.0.3",
    variant: 1,
    trigger: "on_screen_load",
    text: "कृपया अपनी भाषा चुनें।",
    romanTransliteration: "Kripya apni bhasha chunein.",
    englishMeaning: "Please select your language.",
    language: "hi-IN",
    speaker: "priya",
    pace: 0.88,
    pauseAfterMs: 1000,
    maxDurationS: 8,
    emotionalTone: "helpful_guide",
  },
  {
    screenId: "S-0.0.3",
    variant: 2,
    trigger: "on_screen_load",
    text: "अपनी पसंदीदा भाषा चुनें।",
    romanTransliteration: "Apni pasandeeda bhasha chunein.",
    englishMeaning: "Choose your preferred language.",
    language: "hi-IN",
    speaker: "priya",
    pace: 0.88,
    pauseAfterMs: 1000,
    maxDurationS: 8,
    emotionalTone: "warm_respectful",
  },
  {
    screenId: "S-0.0.3",
    variant: 3,
    trigger: "on_screen_load",
    text: "भाषा का चयन करें।",
    romanTransliteration: "Bhasha ka chayan karein.",
    englishMeaning: "Select the language.",
    language: "hi-IN",
    speaker: "priya",
    pace: 0.90,
    pauseAfterMs: 1000,
    maxDurationS: 8,
    emotionalTone: "neutral_informative",
  },
  {
    screenId: "S-0.0.3",
    variant: 4,
    trigger: "on_screen_load",
    text: "यहाँ से भाषा चुनें।",
    romanTransliteration: "Yahan se bhasha chunein.",
    englishMeaning: "Choose language from here.",
    language: "hi-IN",
    speaker: "priya",
    pace: 0.90,
    pauseAfterMs: 1000,
    maxDurationS: 8,
    emotionalTone: "helpful_guide",
  },

  // ==================== TAMIL (ta-IN) ====================
  {
    screenId: "S-0.0.3",
    variant: 1,
    trigger: "on_screen_load",
    text: "தயவுசெய்து உங்கள் மொழியைத் தேர்ந்தெடுக்கவும்.",
    romanTransliteration: "Dayavuseythu ungal mozhiyai therndedukkavum.",
    englishMeaning: "Please select your language.",
    language: "ta-IN",
    speaker: "priya",
    pace: 0.86,
    pauseAfterMs: 1000,
    maxDurationS: 8,
    emotionalTone: "helpful_guide",
  },
  {
    screenId: "S-0.0.3",
    variant: 2,
    trigger: "on_screen_load",
    text: "உங்கள் விருப்பமான மொழியைத் தேர்ந்தெடுக்கவும்.",
    romanTransliteration: "Ungal viruppamana mozhiyai therndedukkavum.",
    englishMeaning: "Choose your preferred language.",
    language: "ta-IN",
    speaker: "priya",
    pace: 0.86,
    pauseAfterMs: 1000,
    maxDurationS: 8,
    emotionalTone: "warm_respectful",
  },
  {
    screenId: "S-0.0.3",
    variant: 3,
    trigger: "on_screen_load",
    text: "மொழியைத் தேர்ந்தெடுக்கவும்.",
    romanTransliteration: "Mozhiyai therndedukkavum.",
    englishMeaning: "Select the language.",
    language: "ta-IN",
    speaker: "priya",
    pace: 0.88,
    pauseAfterMs: 1000,
    maxDurationS: 8,
    emotionalTone: "neutral_informative",
  },
  {
    screenId: "S-0.0.3",
    variant: 4,
    trigger: "on_screen_load",
    text: "இங்கிருந்து மொழியைத் தேர்வு செய்யவும்.",
    romanTransliteration: "Ingingrunthu mozhiyai theravu seyyavum.",
    englishMeaning: "Choose language from here.",
    language: "ta-IN",
    speaker: "priya",
    pace: 0.88,
    pauseAfterMs: 1000,
    maxDurationS: 8,
    emotionalTone: "helpful_guide",
  },

  // ==================== TELUGU (te-IN) ====================
  {
    screenId: "S-0.0.3",
    variant: 1,
    trigger: "on_screen_load",
    text: "దయచేసి మీ భాషను ఎంచుకోండి.",
    romanTransliteration: "Dayachesi mee bhashanu enchukondi.",
    englishMeaning: "Please select your language.",
    language: "te-IN",
    speaker: "priya",
    pace: 0.87,
    pauseAfterMs: 1000,
    maxDurationS: 8,
    emotionalTone: "helpful_guide",
  },
  {
    screenId: "S-0.0.3",
    variant: 2,
    trigger: "on_screen_load",
    text: "మీకు ఇష్టమైన భాషను ఎంచుకోండి.",
    romanTransliteration: "Meeku ishtamaina bhashanu enchukondi.",
    englishMeaning: "Choose your preferred language.",
    language: "te-IN",
    speaker: "priya",
    pace: 0.87,
    pauseAfterMs: 1000,
    maxDurationS: 8,
    emotionalTone: "warm_respectful",
  },
  {
    screenId: "S-0.0.3",
    variant: 3,
    trigger: "on_screen_load",
    text: "భాషను ఎంచుకోండి.",
    romanTransliteration: "Bhashanu enchukondi.",
    englishMeaning: "Select the language.",
    language: "te-IN",
    speaker: "priya",
    pace: 0.89,
    pauseAfterMs: 1000,
    maxDurationS: 8,
    emotionalTone: "neutral_informative",
  },
  {
    screenId: "S-0.0.3",
    variant: 4,
    trigger: "on_screen_load",
    text: "ఇక్కడి నుండి భాషను ఎంచుకోండి.",
    romanTransliteration: "Ikkadi nunundi bhashanu enchukondi.",
    englishMeaning: "Choose language from here.",
    language: "te-IN",
    speaker: "priya",
    pace: 0.89,
    pauseAfterMs: 1000,
    maxDurationS: 8,
    emotionalTone: "helpful_guide",
  },

  // ==================== BENGALI (bn-IN) ====================
  {
    screenId: "S-0.0.3",
    variant: 1,
    trigger: "on_screen_load",
    text: "দয়া করে আপনার ভাষা নির্বাচন করুন।",
    romanTransliteration: "Doya kore apnar bhasha nirbachon korun.",
    englishMeaning: "Please select your language.",
    language: "bn-IN",
    speaker: "priya",
    pace: 0.88,
    pauseAfterMs: 1000,
    maxDurationS: 8,
    emotionalTone: "helpful_guide",
  },
  {
    screenId: "S-0.0.3",
    variant: 2,
    trigger: "on_screen_load",
    text: "আপনার পছন্দের ভাষা নির্বাচন করুন।",
    romanTransliteration: "Apnar pochonder bhasha nirbachon korun.",
    englishMeaning: "Choose your preferred language.",
    language: "bn-IN",
    speaker: "priya",
    pace: 0.88,
    pauseAfterMs: 1000,
    maxDurationS: 8,
    emotionalTone: "warm_respectful",
  },
  {
    screenId: "S-0.0.3",
    variant: 3,
    trigger: "on_screen_load",
    text: "ভাষা নির্বাচন করুন।",
    romanTransliteration: "Bhasha nirbachon korun.",
    englishMeaning: "Select the language.",
    language: "bn-IN",
    speaker: "priya",
    pace: 0.90,
    pauseAfterMs: 1000,
    maxDurationS: 8,
    emotionalTone: "neutral_informative",
  },
  {
    screenId: "S-0.0.3",
    variant: 4,
    trigger: "on_screen_load",
    text: "এখান থেকে ভাষা নির্বাচন করুন।",
    romanTransliteration: "Ekhan theke bhasha nirbachon korun.",
    englishMeaning: "Choose language from here.",
    language: "bn-IN",
    speaker: "priya",
    pace: 0.90,
    pauseAfterMs: 1000,
    maxDurationS: 8,
    emotionalTone: "helpful_guide",
  },

  // ==================== MARATHI (mr-IN) ====================
  {
    screenId: "S-0.0.3",
    variant: 1,
    trigger: "on_screen_load",
    text: "कृपया तुमची भाषा निवडा.",
    romanTransliteration: "Kripya tumchi bhasha nivada.",
    englishMeaning: "Please select your language.",
    language: "mr-IN",
    speaker: "priya",
    pace: 0.89,
    pauseAfterMs: 1000,
    maxDurationS: 8,
    emotionalTone: "helpful_guide",
  },
  {
    screenId: "S-0.0.3",
    variant: 2,
    trigger: "on_screen_load",
    text: "तुमची आवडती भाषा निवडा.",
    romanTransliteration: "Tumchi avadati bhasha nivada.",
    englishMeaning: "Choose your preferred language.",
    language: "mr-IN",
    speaker: "priya",
    pace: 0.89,
    pauseAfterMs: 1000,
    maxDurationS: 8,
    emotionalTone: "warm_respectful",
  },
  {
    screenId: "S-0.0.3",
    variant: 3,
    trigger: "on_screen_load",
    text: "भाषा निवडा.",
    romanTransliteration: "Bhasha nivada.",
    englishMeaning: "Select the language.",
    language: "mr-IN",
    speaker: "priya",
    pace: 0.91,
    pauseAfterMs: 1000,
    maxDurationS: 8,
    emotionalTone: "neutral_informative",
  },
  {
    screenId: "S-0.0.3",
    variant: 4,
    trigger: "on_screen_load",
    text: "येथून भाषा निवडा.",
    romanTransliteration: "Yethun bhasha nivada.",
    englishMeaning: "Choose language from here.",
    language: "mr-IN",
    speaker: "priya",
    pace: 0.91,
    pauseAfterMs: 1000,
    maxDurationS: 8,
    emotionalTone: "helpful_guide",
  },

  // ==================== GUJARATI (gu-IN) ====================
  {
    screenId: "S-0.0.3",
    variant: 1,
    trigger: "on_screen_load",
    text: "કૃપા કરીને તમારી ભાષા પસંદ કરો.",
    romanTransliteration: "Kripa karine tamari bhasha pasand karo.",
    englishMeaning: "Please select your language.",
    language: "gu-IN",
    speaker: "priya",
    pace: 0.88,
    pauseAfterMs: 1000,
    maxDurationS: 8,
    emotionalTone: "helpful_guide",
  },
  {
    screenId: "S-0.0.3",
    variant: 2,
    trigger: "on_screen_load",
    text: "તમારી પસંદગીની ભાષા પસંદ કરો.",
    romanTransliteration: "Tamari pasandgini bhasha pasand karo.",
    englishMeaning: "Choose your preferred language.",
    language: "gu-IN",
    speaker: "priya",
    pace: 0.88,
    pauseAfterMs: 1000,
    maxDurationS: 8,
    emotionalTone: "warm_respectful",
  },
  {
    screenId: "S-0.0.3",
    variant: 3,
    trigger: "on_screen_load",
    text: "ભાષા પસંદ કરો.",
    romanTransliteration: "Bhasha pasand karo.",
    englishMeaning: "Select the language.",
    language: "gu-IN",
    speaker: "priya",
    pace: 0.90,
    pauseAfterMs: 1000,
    maxDurationS: 8,
    emotionalTone: "neutral_informative",
  },
  {
    screenId: "S-0.0.3",
    variant: 4,
    trigger: "on_screen_load",
    text: "અહીંથી ભાષા પસંદ કરો.",
    romanTransliteration: "Ahin thi bhasha pasand karo.",
    englishMeaning: "Choose language from here.",
    language: "gu-IN",
    speaker: "priya",
    pace: 0.90,
    pauseAfterMs: 1000,
    maxDurationS: 8,
    emotionalTone: "helpful_guide",
  },

  // ==================== KANNADA (kn-IN) ====================
  {
    screenId: "S-0.0.3",
    variant: 1,
    trigger: "on_screen_load",
    text: "ದಯವಿಟ್ಟು ನಿಮ್ಮ ಭಾಷೆಯನ್ನು ಆಯ್ಕೆ ಮಾಡಿ.",
    romanTransliteration: "Dayavittu nimma bhashayannu aayke maadi.",
    englishMeaning: "Please select your language.",
    language: "kn-IN",
    speaker: "priya",
    pace: 0.87,
    pauseAfterMs: 1000,
    maxDurationS: 8,
    emotionalTone: "helpful_guide",
  },
  {
    screenId: "S-0.0.3",
    variant: 2,
    trigger: "on_screen_load",
    text: "ನಿಮಗೆ ಇಷ್ಟವಾದ ಭಾಷೆಯನ್ನು ಆಯ್ಕೆ ಮಾಡಿ.",
    romanTransliteration: "Nimage ishtavaada bhashayannu aayke maadi.",
    englishMeaning: "Choose your preferred language.",
    language: "kn-IN",
    speaker: "priya",
    pace: 0.87,
    pauseAfterMs: 1000,
    maxDurationS: 8,
    emotionalTone: "warm_respectful",
  },
  {
    screenId: "S-0.0.3",
    variant: 3,
    trigger: "on_screen_load",
    text: "ಭಾಷೆಯನ್ನು ಆಯ್ಕೆ ಮಾಡಿ.",
    romanTransliteration: "Bhashayannu aayke maadi.",
    englishMeaning: "Select the language.",
    language: "kn-IN",
    speaker: "priya",
    pace: 0.89,
    pauseAfterMs: 1000,
    maxDurationS: 8,
    emotionalTone: "neutral_informative",
  },
  {
    screenId: "S-0.0.3",
    variant: 4,
    trigger: "on_screen_load",
    text: "ಇಲ್ಲಿಂದ ಭಾಷೆಯನ್ನು ಆಯ್ಕೆ ಮಾಡಿ.",
    romanTransliteration: "Illinda bhashayannu aayke maadi.",
    englishMeaning: "Choose language from here.",
    language: "kn-IN",
    speaker: "priya",
    pace: 0.89,
    pauseAfterMs: 1000,
    maxDurationS: 8,
    emotionalTone: "helpful_guide",
  },

  // ==================== MALAYALAM (ml-IN) ====================
  {
    screenId: "S-0.0.3",
    variant: 1,
    trigger: "on_screen_load",
    text: "ദയവായി നിങ്ങളുടെ ഭാഷ തിരഞ്ഞെടുക്കുക.",
    romanTransliteration: "Dayavayi ningalude bhasha thiranjedukkuka.",
    englishMeaning: "Please select your language.",
    language: "ml-IN",
    speaker: "priya",
    pace: 0.86,
    pauseAfterMs: 1000,
    maxDurationS: 8,
    emotionalTone: "helpful_guide",
  },
  {
    screenId: "S-0.0.3",
    variant: 2,
    trigger: "on_screen_load",
    text: "നിങ്ങൾക്ക് ഇഷ്ടമുള്ള ഭാഷ തിരഞ്ഞെടുക്കുക.",
    romanTransliteration: "Ningalkku ishtamulla bhasha thiranjedukkuka.",
    englishMeaning: "Choose your preferred language.",
    language: "ml-IN",
    speaker: "priya",
    pace: 0.86,
    pauseAfterMs: 1000,
    maxDurationS: 8,
    emotionalTone: "warm_respectful",
  },
  {
    screenId: "S-0.0.3",
    variant: 3,
    trigger: "on_screen_load",
    text: "ഭാഷ തിരഞ്ഞെടുക്കുക.",
    romanTransliteration: "Bhasha thiranjedukkuka.",
    englishMeaning: "Select the language.",
    language: "ml-IN",
    speaker: "priya",
    pace: 0.88,
    pauseAfterMs: 1000,
    maxDurationS: 8,
    emotionalTone: "neutral_informative",
  },
  {
    screenId: "S-0.0.3",
    variant: 4,
    trigger: "on_screen_load",
    text: "ഇവിടെ നിന്ന് ഭാഷ തിരഞ്ഞെടുക്കുക.",
    romanTransliteration: "Ivide ninnu bhasha thiranjedukkuka.",
    englishMeaning: "Choose language from here.",
    language: "ml-IN",
    speaker: "priya",
    pace: 0.88,
    pauseAfterMs: 1000,
    maxDurationS: 8,
    emotionalTone: "helpful_guide",
  },

  // ==================== PUNJABI (pa-IN) ====================
  {
    screenId: "S-0.0.3",
    variant: 1,
    trigger: "on_screen_load",
    text: "ਕਿਰਪਾ ਕਰਕੇ ਆਪਣੀ ਭਾਸ਼ਾ ਚੁਣੋ।",
    romanTransliteration: "Kirpa karke apni bhasha chuno.",
    englishMeaning: "Please select your language.",
    language: "pa-IN",
    speaker: "priya",
    pace: 0.88,
    pauseAfterMs: 1000,
    maxDurationS: 8,
    emotionalTone: "helpful_guide",
  },
  {
    screenId: "S-0.0.3",
    variant: 2,
    trigger: "on_screen_load",
    text: "ਆਪਣੀ ਪਸੰਦੀਦਾ ਭਾਸ਼ਾ ਚੁਣੋ।",
    romanTransliteration: "Apni pasandeeda bhasha chuno.",
    englishMeaning: "Choose your preferred language.",
    language: "pa-IN",
    speaker: "priya",
    pace: 0.88,
    pauseAfterMs: 1000,
    maxDurationS: 8,
    emotionalTone: "warm_respectful",
  },
  {
    screenId: "S-0.0.3",
    variant: 3,
    trigger: "on_screen_load",
    text: "ਭਾਸ਼ਾ ਚੁਣੋ।",
    romanTransliteration: "Bhasha chuno.",
    englishMeaning: "Select the language.",
    language: "pa-IN",
    speaker: "priya",
    pace: 0.90,
    pauseAfterMs: 1000,
    maxDurationS: 8,
    emotionalTone: "neutral_informative",
  },
  {
    screenId: "S-0.0.3",
    variant: 4,
    trigger: "on_screen_load",
    text: "ਇੱਥੋਂ ਭਾਸ਼ਾ ਚੁਣੋ।",
    romanTransliteration: "Itthon bhasha chuno.",
    englishMeaning: "Choose language from here.",
    language: "pa-IN",
    speaker: "priya",
    pace: 0.90,
    pauseAfterMs: 1000,
    maxDurationS: 8,
    emotionalTone: "helpful_guide",
  },

  // ==================== ODIA (or-IN) ====================
  {
    screenId: "S-0.0.3",
    variant: 1,
    trigger: "on_screen_load",
    text: "ଦୟାକରି ଆପଣଙ୍କ ଭାଷା ଚୟନ କରନ୍ତୁ।",
    romanTransliteration: "Dayakari aapanka bhasha chayana karantu.",
    englishMeaning: "Please select your language.",
    language: "or-IN",
    speaker: "priya",
    pace: 0.87,
    pauseAfterMs: 1000,
    maxDurationS: 8,
    emotionalTone: "helpful_guide",
  },
  {
    screenId: "S-0.0.3",
    variant: 2,
    trigger: "on_screen_load",
    text: "ଆପଣଙ୍କ ପସନ୍ଦର ଭାଷା ଚୟନ କରନ୍ତୁ।",
    romanTransliteration: "Aapanka pasandara bhasha chayana karantu.",
    englishMeaning: "Choose your preferred language.",
    language: "or-IN",
    speaker: "priya",
    pace: 0.87,
    pauseAfterMs: 1000,
    maxDurationS: 8,
    emotionalTone: "warm_respectful",
  },
  {
    screenId: "S-0.0.3",
    variant: 3,
    trigger: "on_screen_load",
    text: "ଭାଷା ଚୟନ କରନ୍ତୁ।",
    romanTransliteration: "Bhasha chayana karantu.",
    englishMeaning: "Select the language.",
    language: "or-IN",
    speaker: "priya",
    pace: 0.89,
    pauseAfterMs: 1000,
    maxDurationS: 8,
    emotionalTone: "neutral_informative",
  },
  {
    screenId: "S-0.0.3",
    variant: 4,
    trigger: "on_screen_load",
    text: "ଏଠାରୁ ଭାଷା ଚୟନ କରନ୍ତୁ।",
    romanTransliteration: "Etharu bhasha chayana karantu.",
    englishMeaning: "Choose language from here.",
    language: "or-IN",
    speaker: "priya",
    pace: 0.89,
    pauseAfterMs: 1000,
    maxDurationS: 8,
    emotionalTone: "helpful_guide",
  },

  // ==================== ENGLISH (en-IN) ====================
  {
    screenId: "S-0.0.3",
    variant: 1,
    trigger: "on_screen_load",
    text: "Please select your language.",
    romanTransliteration: "Please select your language.",
    englishMeaning: "Please select your language.",
    language: "en-IN",
    speaker: "priya",
    pace: 0.90,
    pauseAfterMs: 1000,
    maxDurationS: 8,
    emotionalTone: "helpful_guide",
  },
  {
    screenId: "S-0.0.3",
    variant: 2,
    trigger: "on_screen_load",
    text: "Choose your preferred language.",
    romanTransliteration: "Choose your preferred language.",
    englishMeaning: "Choose your preferred language.",
    language: "en-IN",
    speaker: "priya",
    pace: 0.90,
    pauseAfterMs: 1000,
    maxDurationS: 8,
    emotionalTone: "warm_respectful",
  },
  {
    screenId: "S-0.0.3",
    variant: 3,
    trigger: "on_screen_load",
    text: "Select the language.",
    romanTransliteration: "Select the language.",
    englishMeaning: "Select the language.",
    language: "en-IN",
    speaker: "priya",
    pace: 0.92,
    pauseAfterMs: 1000,
    maxDurationS: 8,
    emotionalTone: "neutral_informative",
  },
  {
    screenId: "S-0.0.3",
    variant: 4,
    trigger: "on_screen_load",
    text: "Choose language from here.",
    romanTransliteration: "Choose language from here.",
    englishMeaning: "Choose language from here.",
    language: "en-IN",
    speaker: "priya",
    pace: 0.92,
    pauseAfterMs: 1000,
    maxDurationS: 8,
    emotionalTone: "helpful_guide",
  },

  // ==================== BHOJPURI (hi-IN fallback) ====================
  {
    screenId: "S-0.0.3",
    variant: 1,
    trigger: "on_screen_load",
    text: "कृपया अपना भाषा चुनीं।",
    romanTransliteration: "Kripya apna bhasha chuneen.",
    englishMeaning: "Please select your language.",
    language: "hi-IN",
    speaker: "priya",
    pace: 0.88,
    pauseAfterMs: 1000,
    maxDurationS: 8,
    emotionalTone: "helpful_guide",
    fallback: true,
  },
  {
    screenId: "S-0.0.3",
    variant: 2,
    trigger: "on_screen_load",
    text: "अपन पसंदीदा भाषा चुनीं।",
    romanTransliteration: "Apna pasandeeda bhasha chuneen.",
    englishMeaning: "Choose your preferred language.",
    language: "hi-IN",
    speaker: "priya",
    pace: 0.88,
    pauseAfterMs: 1000,
    maxDurationS: 8,
    emotionalTone: "warm_respectful",
    fallback: true,
  },
  {
    screenId: "S-0.0.3",
    variant: 3,
    trigger: "on_screen_load",
    text: "भाषा चुनीं।",
    romanTransliteration: "Bhasha chuneen.",
    englishMeaning: "Select the language.",
    language: "hi-IN",
    speaker: "priya",
    pace: 0.90,
    pauseAfterMs: 1000,
    maxDurationS: 8,
    emotionalTone: "neutral_informative",
    fallback: true,
  },
  {
    screenId: "S-0.0.3",
    variant: 4,
    trigger: "on_screen_load",
    text: "यहाँ से भाषा चुनीं।",
    romanTransliteration: "Yahan se bhasha chuneen.",
    englishMeaning: "Choose language from here.",
    language: "hi-IN",
    speaker: "priya",
    pace: 0.90,
    pauseAfterMs: 1000,
    maxDurationS: 8,
    emotionalTone: "helpful_guide",
    fallback: true,
  },

  // ==================== MAITHILI (hi-IN fallback) ====================
  {
    screenId: "S-0.0.3",
    variant: 1,
    trigger: "on_screen_load",
    text: "कृपया अपन भाषा चुनू।",
    romanTransliteration: "Kripya apna bhasha chunu.",
    englishMeaning: "Please select your language.",
    language: "hi-IN",
    speaker: "priya",
    pace: 0.88,
    pauseAfterMs: 1000,
    maxDurationS: 8,
    emotionalTone: "helpful_guide",
    fallback: true,
  },
  {
    screenId: "S-0.0.3",
    variant: 2,
    trigger: "on_screen_load",
    text: "अपन पसंदीदा भाषा चुनू।",
    romanTransliteration: "Apna pasandeeda bhasha chunu.",
    englishMeaning: "Choose your preferred language.",
    language: "hi-IN",
    speaker: "priya",
    pace: 0.88,
    pauseAfterMs: 1000,
    maxDurationS: 8,
    emotionalTone: "warm_respectful",
    fallback: true,
  },
  {
    screenId: "S-0.0.3",
    variant: 3,
    trigger: "on_screen_load",
    text: "भाषा चुनू।",
    romanTransliteration: "Bhasha chunu.",
    englishMeaning: "Select the language.",
    language: "hi-IN",
    speaker: "priya",
    pace: 0.90,
    pauseAfterMs: 1000,
    maxDurationS: 8,
    emotionalTone: "neutral_informative",
    fallback: true,
  },
  {
    screenId: "S-0.0.3",
    variant: 4,
    trigger: "on_screen_load",
    text: "एतए सँ भाषा चुनू।",
    romanTransliteration: "Etay san bhasha chunu.",
    englishMeaning: "Choose language from here.",
    language: "hi-IN",
    speaker: "priya",
    pace: 0.90,
    pauseAfterMs: 1000,
    maxDurationS: 8,
    emotionalTone: "helpful_guide",
    fallback: true,
  },

  // ==================== SANSKRIT (hi-IN fallback) ====================
  {
    screenId: "S-0.0.3",
    variant: 1,
    trigger: "on_screen_load",
    text: "कृपया स्वभाषां चिनुत।",
    romanTransliteration: "Kripya swabhashaam chinuta.",
    englishMeaning: "Please select your language.",
    language: "hi-IN",
    speaker: "priya",
    pace: 0.85,
    pauseAfterMs: 1000,
    maxDurationS: 8,
    emotionalTone: "warm_respectful",
    fallback: true,
  },
  {
    screenId: "S-0.0.3",
    variant: 2,
    trigger: "on_screen_load",
    text: "स्वप्रियां भाषां चिनुत।",
    romanTransliteration: "Swapriyaam bhashaam chinuta.",
    englishMeaning: "Choose your preferred language.",
    language: "hi-IN",
    speaker: "priya",
    pace: 0.85,
    pauseAfterMs: 1000,
    maxDurationS: 8,
    emotionalTone: "warm_respectful",
    fallback: true,
  },
  {
    screenId: "S-0.0.3",
    variant: 3,
    trigger: "on_screen_load",
    text: "भाषां चिनुत।",
    romanTransliteration: "Bhashaam chinuta.",
    englishMeaning: "Select the language.",
    language: "hi-IN",
    speaker: "priya",
    pace: 0.87,
    pauseAfterMs: 1000,
    maxDurationS: 8,
    emotionalTone: "neutral_informative",
    fallback: true,
  },
  {
    screenId: "S-0.0.3",
    variant: 4,
    trigger: "on_screen_load",
    text: "अतः भाषां चिनुत।",
    romanTransliteration: "Atah bhashaam chinuta.",
    englishMeaning: "Choose language from here.",
    language: "hi-IN",
    speaker: "priya",
    pace: 0.87,
    pauseAfterMs: 1000,
    maxDurationS: 8,
    emotionalTone: "helpful_guide",
    fallback: true,
  },

  // ==================== ASSAMESE (hi-IN fallback) ====================
  {
    screenId: "S-0.0.3",
    variant: 1,
    trigger: "on_screen_load",
    text: "অনুগ্ৰহ কৰি আপোনাৰ ভাষা নিৰ্বাচন কৰক।",
    romanTransliteration: "Anugraha kari apunar bhasha nirbachon korok.",
    englishMeaning: "Please select your language.",
    language: "hi-IN",
    speaker: "priya",
    pace: 0.87,
    pauseAfterMs: 1000,
    maxDurationS: 8,
    emotionalTone: "helpful_guide",
    fallback: true,
  },
  {
    screenId: "S-0.0.3",
    variant: 2,
    trigger: "on_screen_load",
    text: "আপোনাৰ পছন্দৰ ভাষা নিৰ্বাচন কৰক।",
    romanTransliteration: "Apunar pochondor bhasha nirbachon korok.",
    englishMeaning: "Choose your preferred language.",
    language: "hi-IN",
    speaker: "priya",
    pace: 0.87,
    pauseAfterMs: 1000,
    maxDurationS: 8,
    emotionalTone: "warm_respectful",
    fallback: true,
  },
  {
    screenId: "S-0.0.3",
    variant: 3,
    trigger: "on_screen_load",
    text: "ভাষা নিৰ্বাচন কৰক।",
    romanTransliteration: "Bhasha nirbachon korok.",
    englishMeaning: "Select the language.",
    language: "hi-IN",
    speaker: "priya",
    pace: 0.89,
    pauseAfterMs: 1000,
    maxDurationS: 8,
    emotionalTone: "neutral_informative",
    fallback: true,
  },
  {
    screenId: "S-0.0.3",
    variant: 4,
    trigger: "on_screen_load",
    text: "ইয়াৰ পৰা ভাষা নিৰ্বাচন কৰক।",
    romanTransliteration: "Yar pora bhasha nirbachon korok.",
    englishMeaning: "Choose language from here.",
    language: "hi-IN",
    speaker: "priya",
    pace: 0.89,
    pauseAfterMs: 1000,
    maxDurationS: 8,
    emotionalTone: "helpful_guide",
    fallback: true,
  },
];

export default S0_0_3_CITY_SELECTION;
