/**
 * S-0.0.4: Language Selection Screen Scripts
 * Screen: User selects their preferred language
 * Total: 60 scripts (15 languages × 4 variants)
 */

export const S0_0_4_LANGUAGE_SELECTION = [
  // ==================== HINDI (hi-IN) ====================
  {
    screenId: "S-0.0.4",
    variant: 1,
    trigger: "on_screen_load",
    text: "अपनी भाषा चुनें।",
    romanTransliteration: "Apni bhasha chunein.",
    englishMeaning: "Choose your language.",
    language: "hi-IN",
    speaker: "priya",
    pace: 0.88,
    pauseAfterMs: 1100,
    maxDurationS: 8,
    emotionalTone: "helpful_guide",
  },
  {
    screenId: "S-0.0.4",
    variant: 2,
    trigger: "on_screen_load",
    text: "कृपया भाषा का चयन करें।",
    romanTransliteration: "Kripya bhasha ka chayan karein.",
    englishMeaning: "Please select the language.",
    language: "hi-IN",
    speaker: "priya",
    pace: 0.88,
    pauseAfterMs: 1100,
    maxDurationS: 8,
    emotionalTone: "warm_respectful",
  },
  {
    screenId: "S-0.0.4",
    variant: 3,
    trigger: "on_screen_load",
    text: "आप किस भाषा में सुनना चाहेंगे?",
    romanTransliteration: "Aap kis bhasha mein sunna chahenge?",
    englishMeaning: "Which language would you like to hear?",
    language: "hi-IN",
    speaker: "priya",
    pace: 0.86,
    pauseAfterMs: 1100,
    maxDurationS: 8,
    emotionalTone: "warm_respectful",
  },
  {
    screenId: "S-0.0.4",
    variant: 4,
    trigger: "on_screen_load",
    text: "भाषा चुनकर आगे बढ़ें।",
    romanTransliteration: "Bhasha chunkar aage badhein.",
    englishMeaning: "Choose language and proceed.",
    language: "hi-IN",
    speaker: "priya",
    pace: 0.88,
    pauseAfterMs: 1100,
    maxDurationS: 8,
    emotionalTone: "helpful_guide",
  },

  // ==================== TAMIL (ta-IN) ====================
  {
    screenId: "S-0.0.4",
    variant: 1,
    trigger: "on_screen_load",
    text: "உங்கள் மொழியைத் தேர்ந்தெடுக்கவும்.",
    romanTransliteration: "Ungal mozhiyai therndedukkavum.",
    englishMeaning: "Choose your language.",
    language: "ta-IN",
    speaker: "priya",
    pace: 0.86,
    pauseAfterMs: 1100,
    maxDurationS: 8,
    emotionalTone: "helpful_guide",
  },
  {
    screenId: "S-0.0.4",
    variant: 2,
    trigger: "on_screen_load",
    text: "தயவுசெய்து மொழியைத் தேர்ந்தெடுக்கவும்.",
    romanTransliteration: "Dayavuseythu mozhiyai therndedukkavum.",
    englishMeaning: "Please select the language.",
    language: "ta-IN",
    speaker: "priya",
    pace: 0.86,
    pauseAfterMs: 1100,
    maxDurationS: 8,
    emotionalTone: "warm_respectful",
  },
  {
    screenId: "S-0.0.4",
    variant: 3,
    trigger: "on_screen_load",
    text: "நீங்கள் எந்த மொழியில் கேட்க விரும்புகிறீர்கள்?",
    romanTransliteration: "Neengal endha mozhiil ketta virumbukireergal?",
    englishMeaning: "Which language would you like to hear?",
    language: "ta-IN",
    speaker: "priya",
    pace: 0.84,
    pauseAfterMs: 1100,
    maxDurationS: 8,
    emotionalTone: "warm_respectful",
  },
  {
    screenId: "S-0.0.4",
    variant: 4,
    trigger: "on_screen_load",
    text: "மொழியைத் தேர்வு செய்து முன்னேறவும்.",
    romanTransliteration: "Mozhiyai theravu seythu munneravum.",
    englishMeaning: "Choose language and proceed.",
    language: "ta-IN",
    speaker: "priya",
    pace: 0.86,
    pauseAfterMs: 1100,
    maxDurationS: 8,
    emotionalTone: "helpful_guide",
  },

  // ==================== TELUGU (te-IN) ====================
  {
    screenId: "S-0.0.4",
    variant: 1,
    trigger: "on_screen_load",
    text: "మీ భాషను ఎంచుకోండి.",
    romanTransliteration: "Mee bhashanu enchukondi.",
    englishMeaning: "Choose your language.",
    language: "te-IN",
    speaker: "priya",
    pace: 0.87,
    pauseAfterMs: 1100,
    maxDurationS: 8,
    emotionalTone: "helpful_guide",
  },
  {
    screenId: "S-0.0.4",
    variant: 2,
    trigger: "on_screen_load",
    text: "దయచేసి భాషను ఎంచుకోండి.",
    romanTransliteration: "Dayachesi bhashanu enchukondi.",
    englishMeaning: "Please select the language.",
    language: "te-IN",
    speaker: "priya",
    pace: 0.87,
    pauseAfterMs: 1100,
    maxDurationS: 8,
    emotionalTone: "warm_respectful",
  },
  {
    screenId: "S-0.0.4",
    variant: 3,
    trigger: "on_screen_load",
    text: "మీరు ఏ భాషలో వినాలనుకుంటున్నారు?",
    romanTransliteration: "Meeru ye bhashalo vinalanukuntunnaru?",
    englishMeaning: "Which language would you like to hear?",
    language: "te-IN",
    speaker: "priya",
    pace: 0.85,
    pauseAfterMs: 1100,
    maxDurationS: 8,
    emotionalTone: "warm_respectful",
  },
  {
    screenId: "S-0.0.4",
    variant: 4,
    trigger: "on_screen_load",
    text: "భాషను ఎంచుకుని ముందుకు వెళ్లండి.",
    romanTransliteration: "Bhashanu enchukuni munduku vellandi.",
    englishMeaning: "Choose language and proceed.",
    language: "te-IN",
    speaker: "priya",
    pace: 0.87,
    pauseAfterMs: 1100,
    maxDurationS: 8,
    emotionalTone: "helpful_guide",
  },

  // ==================== BENGALI (bn-IN) ====================
  {
    screenId: "S-0.0.4",
    variant: 1,
    trigger: "on_screen_load",
    text: "আপনার ভাষা নির্বাচন করুন।",
    romanTransliteration: "Apnar bhasha nirbachon korun.",
    englishMeaning: "Choose your language.",
    language: "bn-IN",
    speaker: "priya",
    pace: 0.88,
    pauseAfterMs: 1100,
    maxDurationS: 8,
    emotionalTone: "helpful_guide",
  },
  {
    screenId: "S-0.0.4",
    variant: 2,
    trigger: "on_screen_load",
    text: "দয়া করে ভাষা নির্বাচন করুন।",
    romanTransliteration: "Doya kore bhasha nirbachon korun.",
    englishMeaning: "Please select the language.",
    language: "bn-IN",
    speaker: "priya",
    pace: 0.88,
    pauseAfterMs: 1100,
    maxDurationS: 8,
    emotionalTone: "warm_respectful",
  },
  {
    screenId: "S-0.0.4",
    variant: 3,
    trigger: "on_screen_load",
    text: "আপনি কোন ভাষায় শুনতে চান?",
    romanTransliteration: "Apni kon bhashay shunte chan?",
    englishMeaning: "Which language would you like to hear?",
    language: "bn-IN",
    speaker: "priya",
    pace: 0.86,
    pauseAfterMs: 1100,
    maxDurationS: 8,
    emotionalTone: "warm_respectful",
  },
  {
    screenId: "S-0.0.4",
    variant: 4,
    trigger: "on_screen_load",
    text: "ভাষা নির্বাচন করে এগিয়ে যান।",
    romanTransliteration: "Bhasha nirbachon kore egiye yan.",
    englishMeaning: "Choose language and proceed.",
    language: "bn-IN",
    speaker: "priya",
    pace: 0.88,
    pauseAfterMs: 1100,
    maxDurationS: 8,
    emotionalTone: "helpful_guide",
  },

  // ==================== MARATHI (mr-IN) ====================
  {
    screenId: "S-0.0.4",
    variant: 1,
    trigger: "on_screen_load",
    text: "तुमची भाषा निवडा.",
    romanTransliteration: "Tumchi bhasha nivada.",
    englishMeaning: "Choose your language.",
    language: "mr-IN",
    speaker: "priya",
    pace: 0.89,
    pauseAfterMs: 1100,
    maxDurationS: 8,
    emotionalTone: "helpful_guide",
  },
  {
    screenId: "S-0.0.4",
    variant: 2,
    trigger: "on_screen_load",
    text: "कृपया भाषा निवडा.",
    romanTransliteration: "Kripya bhasha nivada.",
    englishMeaning: "Please select the language.",
    language: "mr-IN",
    speaker: "priya",
    pace: 0.89,
    pauseAfterMs: 1100,
    maxDurationS: 8,
    emotionalTone: "warm_respectful",
  },
  {
    screenId: "S-0.0.4",
    variant: 3,
    trigger: "on_screen_load",
    text: "तुम्हाला कोणत्या भाषेत ऐकायचे आहे?",
    romanTransliteration: "Tumhala kontya bhashet aikayche ahe?",
    englishMeaning: "Which language would you like to hear?",
    language: "mr-IN",
    speaker: "priya",
    pace: 0.87,
    pauseAfterMs: 1100,
    maxDurationS: 8,
    emotionalTone: "warm_respectful",
  },
  {
    screenId: "S-0.0.4",
    variant: 4,
    trigger: "on_screen_load",
    text: "भाषा निवडून पुढे जा.",
    romanTransliteration: "Bhasha nivadun pudhe ja.",
    englishMeaning: "Choose language and proceed.",
    language: "mr-IN",
    speaker: "priya",
    pace: 0.89,
    pauseAfterMs: 1100,
    maxDurationS: 8,
    emotionalTone: "helpful_guide",
  },

  // ==================== GUJARATI (gu-IN) ====================
  {
    screenId: "S-0.0.4",
    variant: 1,
    trigger: "on_screen_load",
    text: "તમારી ભાષા પસંદ કરો.",
    romanTransliteration: "Tamari bhasha pasand karo.",
    englishMeaning: "Choose your language.",
    language: "gu-IN",
    speaker: "priya",
    pace: 0.88,
    pauseAfterMs: 1100,
    maxDurationS: 8,
    emotionalTone: "helpful_guide",
  },
  {
    screenId: "S-0.0.4",
    variant: 2,
    trigger: "on_screen_load",
    text: "કૃપા કરીને ભાષા પસંદ કરો.",
    romanTransliteration: "Kripa karine bhasha pasand karo.",
    englishMeaning: "Please select the language.",
    language: "gu-IN",
    speaker: "priya",
    pace: 0.88,
    pauseAfterMs: 1100,
    maxDurationS: 8,
    emotionalTone: "warm_respectful",
  },
  {
    screenId: "S-0.0.4",
    variant: 3,
    trigger: "on_screen_load",
    text: "તમે કઈ ભાષામાં સાંભળવા માંગો છો?",
    romanTransliteration: "Tame kai bhashama sambhalavu mango cho?",
    englishMeaning: "Which language would you like to hear?",
    language: "gu-IN",
    speaker: "priya",
    pace: 0.86,
    pauseAfterMs: 1100,
    maxDurationS: 8,
    emotionalTone: "warm_respectful",
  },
  {
    screenId: "S-0.0.4",
    variant: 4,
    trigger: "on_screen_load",
    text: "ભાષા પસંદ કરીને આગળ વધો.",
    romanTransliteration: "Bhasha pasand karine aagal vadho.",
    englishMeaning: "Choose language and proceed.",
    language: "gu-IN",
    speaker: "priya",
    pace: 0.88,
    pauseAfterMs: 1100,
    maxDurationS: 8,
    emotionalTone: "helpful_guide",
  },

  // ==================== KANNADA (kn-IN) ====================
  {
    screenId: "S-0.0.4",
    variant: 1,
    trigger: "on_screen_load",
    text: "ನಿಮ್ಮ ಭಾಷೆಯನ್ನು ಆಯ್ಕೆ ಮಾಡಿ.",
    romanTransliteration: "Nimma bhashayannu aayke maadi.",
    englishMeaning: "Choose your language.",
    language: "kn-IN",
    speaker: "priya",
    pace: 0.87,
    pauseAfterMs: 1100,
    maxDurationS: 8,
    emotionalTone: "helpful_guide",
  },
  {
    screenId: "S-0.0.4",
    variant: 2,
    trigger: "on_screen_load",
    text: "ದಯವಿಟ್ಟು ಭಾಷೆಯನ್ನು ಆಯ್ಕೆ ಮಾಡಿ.",
    romanTransliteration: "Dayavittu bhashayannu aayke maadi.",
    englishMeaning: "Please select the language.",
    language: "kn-IN",
    speaker: "priya",
    pace: 0.87,
    pauseAfterMs: 1100,
    maxDurationS: 8,
    emotionalTone: "warm_respectful",
  },
  {
    screenId: "S-0.0.4",
    variant: 3,
    trigger: "on_screen_load",
    text: "ನೀವು ಯಾವ ಭಾಷೆಯಲ್ಲಿ ಕೇಳಲು ಬಯಸುತ್ತೀರಿ?",
    romanTransliteration: "Neevu yaava bhashayalli kelalu bayasuttiri?",
    englishMeaning: "Which language would you like to hear?",
    language: "kn-IN",
    speaker: "priya",
    pace: 0.85,
    pauseAfterMs: 1100,
    maxDurationS: 8,
    emotionalTone: "warm_respectful",
  },
  {
    screenId: "S-0.0.4",
    variant: 4,
    trigger: "on_screen_load",
    text: "ಭಾಷೆಯನ್ನು ಆಯ್ಕೆ ಮಾಡಿ ಮುಂದುವರಿಯಿರಿ.",
    romanTransliteration: "Bhashayannu aayke maadi munduvariyiri.",
    englishMeaning: "Choose language and proceed.",
    language: "kn-IN",
    speaker: "priya",
    pace: 0.87,
    pauseAfterMs: 1100,
    maxDurationS: 8,
    emotionalTone: "helpful_guide",
  },

  // ==================== MALAYALAM (ml-IN) ====================
  {
    screenId: "S-0.0.4",
    variant: 1,
    trigger: "on_screen_load",
    text: "നിങ്ങളുടെ ഭാഷ തിരഞ്ഞെടുക്കുക.",
    romanTransliteration: "Ningalude bhasha thiranjedukkuka.",
    englishMeaning: "Choose your language.",
    language: "ml-IN",
    speaker: "priya",
    pace: 0.86,
    pauseAfterMs: 1100,
    maxDurationS: 8,
    emotionalTone: "helpful_guide",
  },
  {
    screenId: "S-0.0.4",
    variant: 2,
    trigger: "on_screen_load",
    text: "ദയവായി ഭാഷ തിരഞ്ഞെടുക്കുക.",
    romanTransliteration: "Dayavayi bhasha thiranjedukkuka.",
    englishMeaning: "Please select the language.",
    language: "ml-IN",
    speaker: "priya",
    pace: 0.86,
    pauseAfterMs: 1100,
    maxDurationS: 8,
    emotionalTone: "warm_respectful",
  },
  {
    screenId: "S-0.0.4",
    variant: 3,
    trigger: "on_screen_load",
    text: "നിങ്ങൾ ഏത് ഭാഷയിലാണ് കേൾക്കാൻ ആഗ്രഹിക്കുന്നത്?",
    romanTransliteration: "Ningal ethu bhashayilaan kelkkaan aagrahikkunnathu?",
    englishMeaning: "Which language would you like to hear?",
    language: "ml-IN",
    speaker: "priya",
    pace: 0.84,
    pauseAfterMs: 1100,
    maxDurationS: 8,
    emotionalTone: "warm_respectful",
  },
  {
    screenId: "S-0.0.4",
    variant: 4,
    trigger: "on_screen_load",
    text: "ഭാഷ തിരഞ്ഞെടുത്ത് മുന്നോട്ട് പോകുക.",
    romanTransliteration: "Bhasha thiranjeduthu munnotu pokuka.",
    englishMeaning: "Choose language and proceed.",
    language: "ml-IN",
    speaker: "priya",
    pace: 0.86,
    pauseAfterMs: 1100,
    maxDurationS: 8,
    emotionalTone: "helpful_guide",
  },

  // ==================== PUNJABI (pa-IN) ====================
  {
    screenId: "S-0.0.4",
    variant: 1,
    trigger: "on_screen_load",
    text: "ਆਪਣੀ ਭਾਸ਼ਾ ਚੁਣੋ।",
    romanTransliteration: "Apni bhasha chuno.",
    englishMeaning: "Choose your language.",
    language: "pa-IN",
    speaker: "priya",
    pace: 0.88,
    pauseAfterMs: 1100,
    maxDurationS: 8,
    emotionalTone: "helpful_guide",
  },
  {
    screenId: "S-0.0.4",
    variant: 2,
    trigger: "on_screen_load",
    text: "ਕਿਰਪਾ ਕਰਕੇ ਭਾਸ਼ਾ ਚੁਣੋ।",
    romanTransliteration: "Kirpa karke bhasha chuno.",
    englishMeaning: "Please select the language.",
    language: "pa-IN",
    speaker: "priya",
    pace: 0.88,
    pauseAfterMs: 1100,
    maxDurationS: 8,
    emotionalTone: "warm_respectful",
  },
  {
    screenId: "S-0.0.4",
    variant: 3,
    trigger: "on_screen_load",
    text: "ਤੁਸੀਂ ਕਿਹੜੀ ਭਾਸ਼ਾ ਵਿੱਚ ਸੁਣਨਾ ਚਾਹੁੰਦੇ ਹੋ?",
    romanTransliteration: "Tusī kihṛī bhāshā vich sunnā chāhundē hō?",
    englishMeaning: "Which language would you like to hear?",
    language: "pa-IN",
    speaker: "priya",
    pace: 0.86,
    pauseAfterMs: 1100,
    maxDurationS: 8,
    emotionalTone: "warm_respectful",
  },
  {
    screenId: "S-0.0.4",
    variant: 4,
    trigger: "on_screen_load",
    text: "ਭਾਸ਼ਾ ਚੁਣ ਕੇ ਅੱਗੇ ਵਧੋ।",
    romanTransliteration: "Bhasha chun ke agge vadho.",
    englishMeaning: "Choose language and proceed.",
    language: "pa-IN",
    speaker: "priya",
    pace: 0.88,
    pauseAfterMs: 1100,
    maxDurationS: 8,
    emotionalTone: "helpful_guide",
  },

  // ==================== ODIA (or-IN) ====================
  {
    screenId: "S-0.0.4",
    variant: 1,
    trigger: "on_screen_load",
    text: "ଆପଣଙ୍କ ଭାଷା ଚୟନ କରନ୍ତୁ।",
    romanTransliteration: "Aapanka bhasha chayana karantu.",
    englishMeaning: "Choose your language.",
    language: "or-IN",
    speaker: "priya",
    pace: 0.87,
    pauseAfterMs: 1100,
    maxDurationS: 8,
    emotionalTone: "helpful_guide",
  },
  {
    screenId: "S-0.0.4",
    variant: 2,
    trigger: "on_screen_load",
    text: "ଦୟାକରି ଭାଷା ଚୟନ କରନ୍ତୁ।",
    romanTransliteration: "Dayakari bhasha chayana karantu.",
    englishMeaning: "Please select the language.",
    language: "or-IN",
    speaker: "priya",
    pace: 0.87,
    pauseAfterMs: 1100,
    maxDurationS: 8,
    emotionalTone: "warm_respectful",
  },
  {
    screenId: "S-0.0.4",
    variant: 3,
    trigger: "on_screen_load",
    text: "ଆପଣ କେଉଁ ଭାଷାରେ ଶୁଣିବାକୁ ଚାହାଁନ୍ତି?",
    romanTransliteration: "Aapan kaun bhashare shunibaku chahanti?",
    englishMeaning: "Which language would you like to hear?",
    language: "or-IN",
    speaker: "priya",
    pace: 0.85,
    pauseAfterMs: 1100,
    maxDurationS: 8,
    emotionalTone: "warm_respectful",
  },
  {
    screenId: "S-0.0.4",
    variant: 4,
    trigger: "on_screen_load",
    text: "ଭାଷା ଚୟନ କରି ଆଗକୁ ବଢ଼ନ୍ତୁ।",
    romanTransliteration: "Bhasha chayana kari aagu badhantu.",
    englishMeaning: "Choose language and proceed.",
    language: "or-IN",
    speaker: "priya",
    pace: 0.87,
    pauseAfterMs: 1100,
    maxDurationS: 8,
    emotionalTone: "helpful_guide",
  },

  // ==================== ENGLISH (en-IN) ====================
  {
    screenId: "S-0.0.4",
    variant: 1,
    trigger: "on_screen_load",
    text: "Choose your language.",
    romanTransliteration: "Choose your language.",
    englishMeaning: "Choose your language.",
    language: "en-IN",
    speaker: "priya",
    pace: 0.90,
    pauseAfterMs: 1100,
    maxDurationS: 8,
    emotionalTone: "helpful_guide",
  },
  {
    screenId: "S-0.0.4",
    variant: 2,
    trigger: "on_screen_load",
    text: "Please select the language.",
    romanTransliteration: "Please select the language.",
    englishMeaning: "Please select the language.",
    language: "en-IN",
    speaker: "priya",
    pace: 0.90,
    pauseAfterMs: 1100,
    maxDurationS: 8,
    emotionalTone: "warm_respectful",
  },
  {
    screenId: "S-0.0.4",
    variant: 3,
    trigger: "on_screen_load",
    text: "Which language would you like to hear?",
    romanTransliteration: "Which language would you like to hear?",
    englishMeaning: "Which language would you like to hear?",
    language: "en-IN",
    speaker: "priya",
    pace: 0.88,
    pauseAfterMs: 1100,
    maxDurationS: 8,
    emotionalTone: "warm_respectful",
  },
  {
    screenId: "S-0.0.4",
    variant: 4,
    trigger: "on_screen_load",
    text: "Choose language and proceed.",
    romanTransliteration: "Choose language and proceed.",
    englishMeaning: "Choose language and proceed.",
    language: "en-IN",
    speaker: "priya",
    pace: 0.90,
    pauseAfterMs: 1100,
    maxDurationS: 8,
    emotionalTone: "helpful_guide",
  },

  // ==================== BHOJPURI (hi-IN fallback) ====================
  {
    screenId: "S-0.0.4",
    variant: 1,
    trigger: "on_screen_load",
    text: "अपना भाषा चुनीं।",
    romanTransliteration: "Apna bhasha chuneen.",
    englishMeaning: "Choose your language.",
    language: "hi-IN",
    speaker: "priya",
    pace: 0.88,
    pauseAfterMs: 1100,
    maxDurationS: 8,
    emotionalTone: "helpful_guide",
    fallback: true,
  },
  {
    screenId: "S-0.0.4",
    variant: 2,
    trigger: "on_screen_load",
    text: "कृपया भाषा चुनीं।",
    romanTransliteration: "Kripya bhasha chuneen.",
    englishMeaning: "Please select the language.",
    language: "hi-IN",
    speaker: "priya",
    pace: 0.88,
    pauseAfterMs: 1100,
    maxDurationS: 8,
    emotionalTone: "warm_respectful",
    fallback: true,
  },
  {
    screenId: "S-0.0.4",
    variant: 3,
    trigger: "on_screen_load",
    text: "काहे भाषा में सुनना चाहत बानी?",
    romanTransliteration: "Kahe bhasha mein sunna chaht bani?",
    englishMeaning: "Which language would you like to hear?",
    language: "hi-IN",
    speaker: "priya",
    pace: 0.86,
    pauseAfterMs: 1100,
    maxDurationS: 8,
    emotionalTone: "warm_respectful",
    fallback: true,
  },
  {
    screenId: "S-0.0.4",
    variant: 4,
    trigger: "on_screen_load",
    text: "भाषा चुनीं आ आगे बढ़ीं।",
    romanTransliteration: "Bhasha chuneen a aage badheen.",
    englishMeaning: "Choose language and proceed.",
    language: "hi-IN",
    speaker: "priya",
    pace: 0.88,
    pauseAfterMs: 1100,
    maxDurationS: 8,
    emotionalTone: "helpful_guide",
    fallback: true,
  },

  // ==================== MAITHILI (hi-IN fallback) ====================
  {
    screenId: "S-0.0.4",
    variant: 1,
    trigger: "on_screen_load",
    text: "अपन भाषा चुनू।",
    romanTransliteration: "Apna bhasha chunu.",
    englishMeaning: "Choose your language.",
    language: "hi-IN",
    speaker: "priya",
    pace: 0.88,
    pauseAfterMs: 1100,
    maxDurationS: 8,
    emotionalTone: "helpful_guide",
    fallback: true,
  },
  {
    screenId: "S-0.0.4",
    variant: 2,
    trigger: "on_screen_load",
    text: "कृपया भाषा चुनू।",
    romanTransliteration: "Kripya bhasha chunu.",
    englishMeaning: "Please select the language.",
    language: "hi-IN",
    speaker: "priya",
    pace: 0.88,
    pauseAfterMs: 1100,
    maxDurationS: 8,
    emotionalTone: "warm_respectful",
    fallback: true,
  },
  {
    screenId: "S-0.0.4",
    variant: 3,
    trigger: "on_screen_load",
    text: "अहाँ केहे भाषामे सुनना चाहैत छी?",
    romanTransliteration: "Aahan kehe bhashame sunna chahait chhi?",
    englishMeaning: "Which language would you like to hear?",
    language: "hi-IN",
    speaker: "priya",
    pace: 0.86,
    pauseAfterMs: 1100,
    maxDurationS: 8,
    emotionalTone: "warm_respectful",
    fallback: true,
  },
  {
    screenId: "S-0.0.4",
    variant: 4,
    trigger: "on_screen_load",
    text: "भाषा चुनू आ आगू बढ़ू।",
    romanTransliteration: "Bhasha chunu a aagu badhu.",
    englishMeaning: "Choose language and proceed.",
    language: "hi-IN",
    speaker: "priya",
    pace: 0.88,
    pauseAfterMs: 1100,
    maxDurationS: 8,
    emotionalTone: "helpful_guide",
    fallback: true,
  },

  // ==================== SANSKRIT (hi-IN fallback) ====================
  {
    screenId: "S-0.0.4",
    variant: 1,
    trigger: "on_screen_load",
    text: "स्वभाषां चिनुत।",
    romanTransliteration: "Swabhashaam chinuta.",
    englishMeaning: "Choose your language.",
    language: "hi-IN",
    speaker: "priya",
    pace: 0.85,
    pauseAfterMs: 1100,
    maxDurationS: 8,
    emotionalTone: "warm_respectful",
    fallback: true,
  },
  {
    screenId: "S-0.0.4",
    variant: 2,
    trigger: "on_screen_load",
    text: "कृपया भाषां चिनुत।",
    romanTransliteration: "Kripya bhashaam chinuta.",
    englishMeaning: "Please select the language.",
    language: "hi-IN",
    speaker: "priya",
    pace: 0.85,
    pauseAfterMs: 1100,
    maxDurationS: 8,
    emotionalTone: "warm_respectful",
    fallback: true,
  },
  {
    screenId: "S-0.0.4",
    variant: 3,
    trigger: "on_screen_load",
    text: "कां भाषायां श्रोतुमिच्छथ?",
    romanTransliteration: "Kaam bhashaayaam shrotumicchatha?",
    englishMeaning: "Which language would you like to hear?",
    language: "hi-IN",
    speaker: "priya",
    pace: 0.83,
    pauseAfterMs: 1100,
    maxDurationS: 8,
    emotionalTone: "warm_respectful",
    fallback: true,
  },
  {
    screenId: "S-0.0.4",
    variant: 4,
    trigger: "on_screen_load",
    text: "भाषां चित्वा अग्रं गच्छत।",
    romanTransliteration: "Bhashaam chitvaa agram gacchata.",
    englishMeaning: "Choose language and proceed.",
    language: "hi-IN",
    speaker: "priya",
    pace: 0.85,
    pauseAfterMs: 1100,
    maxDurationS: 8,
    emotionalTone: "helpful_guide",
    fallback: true,
  },

  // ==================== ASSAMESE (hi-IN fallback) ====================
  {
    screenId: "S-0.0.4",
    variant: 1,
    trigger: "on_screen_load",
    text: "আপোনাৰ ভাষা নিৰ্বাচন কৰক।",
    romanTransliteration: "Apunar bhasha nirbachon korok.",
    englishMeaning: "Choose your language.",
    language: "hi-IN",
    speaker: "priya",
    pace: 0.87,
    pauseAfterMs: 1100,
    maxDurationS: 8,
    emotionalTone: "helpful_guide",
    fallback: true,
  },
  {
    screenId: "S-0.0.4",
    variant: 2,
    trigger: "on_screen_load",
    text: "অনুগ্ৰহ কৰি ভাষা নিৰ্বাচন কৰক।",
    romanTransliteration: "Anugraha kori bhasha nirbachon korok.",
    englishMeaning: "Please select the language.",
    language: "hi-IN",
    speaker: "priya",
    pace: 0.87,
    pauseAfterMs: 1100,
    maxDurationS: 8,
    emotionalTone: "warm_respectful",
    fallback: true,
  },
  {
    screenId: "S-0.0.4",
    variant: 3,
    trigger: "on_screen_load",
    text: "আপুনি কোন ভাষাত শুনিব বিচাৰে?",
    romanTransliteration: "Apuni kon bhasat shunibi bisare?",
    englishMeaning: "Which language would you like to hear?",
    language: "hi-IN",
    speaker: "priya",
    pace: 0.85,
    pauseAfterMs: 1100,
    maxDurationS: 8,
    emotionalTone: "warm_respectful",
    fallback: true,
  },
  {
    screenId: "S-0.0.4",
    variant: 4,
    trigger: "on_screen_load",
    text: "ভাষা নিৰ্বাচন কৰি আগবাঢ়ক।",
    romanTransliteration: "Bhasha nirbachon kori aagbarhak.",
    englishMeaning: "Choose language and proceed.",
    language: "hi-IN",
    speaker: "priya",
    pace: 0.87,
    pauseAfterMs: 1100,
    maxDurationS: 8,
    emotionalTone: "helpful_guide",
    fallback: true,
  },
];

export default S0_0_4_LANGUAGE_SELECTION;
