/**
 * S-0.0.5: Permission Explanation Screen Scripts
 * Screen: Explain why location permission is needed
 * Total: 60 scripts (15 languages × 4 variants)
 */

export const S0_0_5_PERMISSION_EXPLANATION = [
  // ==================== HINDI (hi-IN) ====================
  {
    screenId: "S-0.0.5",
    variant: 1,
    trigger: "on_screen_load",
    text: "हमें आपकी लोकेशन की आवश्यकता है।",
    romanTransliteration: "Hamein aapki location ki aavashyakta hai.",
    englishMeaning: "We need your location.",
    language: "hi-IN",
    speaker: "priya",
    pace: 0.85,
    pauseAfterMs: 1200,
    maxDurationS: 8,
    emotionalTone: "reassuring",
  },
  {
    screenId: "S-0.0.5",
    variant: 2,
    trigger: "on_screen_load",
    text: "लोकेशन से हम बेहतर सेवा दे सकते हैं।",
    romanTransliteration: "Location se hum behtar seva de sakte hain.",
    englishMeaning: "Location helps us provide better service.",
    language: "hi-IN",
    speaker: "priya",
    pace: 0.85,
    pauseAfterMs: 1200,
    maxDurationS: 8,
    emotionalTone: "helpful_guide",
  },
  {
    screenId: "S-0.0.5",
    variant: 3,
    trigger: "on_screen_load",
    text: "यह सुरक्षित है। हम डेटा सुरक्षित रखते हैं।",
    romanTransliteration: "Yeh surakshit hai. Hum data surakshit rakhte hain.",
    englishMeaning: "It's safe. We keep data secure.",
    language: "hi-IN",
    speaker: "priya",
    pace: 0.82,
    pauseAfterMs: 1200,
    maxDurationS: 8,
    emotionalTone: "reassuring",
  },
  {
    screenId: "S-0.0.5",
    variant: 4,
    trigger: "on_screen_load",
    text: "कृपया लोकेशन अनुमति दें।",
    romanTransliteration: "Kripya location anumati dein.",
    englishMeaning: "Please give location permission.",
    language: "hi-IN",
    speaker: "priya",
    pace: 0.88,
    pauseAfterMs: 1200,
    maxDurationS: 8,
    emotionalTone: "warm_respectful",
  },

  // ==================== TAMIL (ta-IN) ====================
  {
    screenId: "S-0.0.5",
    variant: 1,
    trigger: "on_screen_load",
    text: "எங்களுக்கு உங்கள் இருப்பிடம் தேவை.",
    romanTransliteration: "Engalukku ungal iruppidam thevai.",
    englishMeaning: "We need your location.",
    language: "ta-IN",
    speaker: "priya",
    pace: 0.83,
    pauseAfterMs: 1200,
    maxDurationS: 8,
    emotionalTone: "reassuring",
  },
  {
    screenId: "S-0.0.5",
    variant: 2,
    trigger: "on_screen_load",
    text: "இருப்பிடம் மூலம் சிறந்த சேவை வழங்கலாம்.",
    romanTransliteration: "Iruppidam moolam sirandha sevai vazhangalam.",
    englishMeaning: "Location helps us provide better service.",
    language: "ta-IN",
    speaker: "priya",
    pace: 0.83,
    pauseAfterMs: 1200,
    maxDurationS: 8,
    emotionalTone: "helpful_guide",
  },
  {
    screenId: "S-0.0.5",
    variant: 3,
    trigger: "on_screen_load",
    text: "இது பாதுகாப்பானது. தரவு பாதுகாக்கப்படும்.",
    romanTransliteration: "Idhu paadhukappamaanadhu. Dataavu paadhukkapadum.",
    englishMeaning: "It's safe. Data will be secured.",
    language: "ta-IN",
    speaker: "priya",
    pace: 0.80,
    pauseAfterMs: 1200,
    maxDurationS: 8,
    emotionalTone: "reassuring",
  },
  {
    screenId: "S-0.0.5",
    variant: 4,
    trigger: "on_screen_load",
    text: "தயவுசெய்து இருப்பிட அனுமதி வழங்கவும்.",
    romanTransliteration: "Dayavuseythu iruppida anumathi vazhangavum.",
    englishMeaning: "Please give location permission.",
    language: "ta-IN",
    speaker: "priya",
    pace: 0.85,
    pauseAfterMs: 1200,
    maxDurationS: 8,
    emotionalTone: "warm_respectful",
  },

  // ==================== TELUGU (te-IN) ====================
  {
    screenId: "S-0.0.5",
    variant: 1,
    trigger: "on_screen_load",
    text: "మాకు మీ లొకేషన్ అవసరం.",
    romanTransliteration: "Maaku mee location avasaram.",
    englishMeaning: "We need your location.",
    language: "te-IN",
    speaker: "priya",
    pace: 0.84,
    pauseAfterMs: 1200,
    maxDurationS: 8,
    emotionalTone: "reassuring",
  },
  {
    screenId: "S-0.0.5",
    variant: 2,
    trigger: "on_screen_load",
    text: "లొకేషన్ ద్వారా మేము మెరుగైన సేవ ఇవ్వగలం.",
    romanTransliteration: "Location dwaaraa memu merugaina seva ivvagalam.",
    englishMeaning: "Location helps us provide better service.",
    language: "te-IN",
    speaker: "priya",
    pace: 0.84,
    pauseAfterMs: 1200,
    maxDurationS: 8,
    emotionalTone: "helpful_guide",
  },
  {
    screenId: "S-0.0.5",
    variant: 3,
    trigger: "on_screen_load",
    text: "ఇది సురక్షితం. డేటా సురక్షితంగా ఉంటుంది.",
    romanTransliteration: "Idhi surakshitam. Data surakshitanga untundi.",
    englishMeaning: "It's safe. Data will be secure.",
    language: "te-IN",
    speaker: "priya",
    pace: 0.82,
    pauseAfterMs: 1200,
    maxDurationS: 8,
    emotionalTone: "reassuring",
  },
  {
    screenId: "S-0.0.5",
    variant: 4,
    trigger: "on_screen_load",
    text: "దయచేసి లొకేషన్ అనుమతి ఇవ్వండి.",
    romanTransliteration: "Dayachesi location anumati ivvandi.",
    englishMeaning: "Please give location permission.",
    language: "te-IN",
    speaker: "priya",
    pace: 0.86,
    pauseAfterMs: 1200,
    maxDurationS: 8,
    emotionalTone: "warm_respectful",
  },

  // ==================== BENGALI (bn-IN) ====================
  {
    screenId: "S-0.0.5",
    variant: 1,
    trigger: "on_screen_load",
    text: "আমাদের আপনার লোকেশন প্রয়োজন।",
    romanTransliteration: "Amader apnar location proyojon.",
    englishMeaning: "We need your location.",
    language: "bn-IN",
    speaker: "priya",
    pace: 0.85,
    pauseAfterMs: 1200,
    maxDurationS: 8,
    emotionalTone: "reassuring",
  },
  {
    screenId: "S-0.0.5",
    variant: 2,
    trigger: "on_screen_load",
    text: "লোকেশন দিয়ে আমরা ভালো সেবা দিতে পারি।",
    romanTransliteration: "Location diye amra bhalo seva dite pari.",
    englishMeaning: "Location helps us provide better service.",
    language: "bn-IN",
    speaker: "priya",
    pace: 0.85,
    pauseAfterMs: 1200,
    maxDurationS: 8,
    emotionalTone: "helpful_guide",
  },
  {
    screenId: "S-0.0.5",
    variant: 3,
    trigger: "on_screen_load",
    text: "এটি নিরাপদ। ডেটা সুরক্ষিত রাখা হয়।",
    romanTransliteration: "Eta nirapod. Data surakkhit rakha hoy.",
    englishMeaning: "It's safe. Data is kept secure.",
    language: "bn-IN",
    speaker: "priya",
    pace: 0.83,
    pauseAfterMs: 1200,
    maxDurationS: 8,
    emotionalTone: "reassuring",
  },
  {
    screenId: "S-0.0.5",
    variant: 4,
    trigger: "on_screen_load",
    text: "দয়া করে লোকেশন অনুমতি দিন।",
    romanTransliteration: "Doya kore location anumati din.",
    englishMeaning: "Please give location permission.",
    language: "bn-IN",
    speaker: "priya",
    pace: 0.87,
    pauseAfterMs: 1200,
    maxDurationS: 8,
    emotionalTone: "warm_respectful",
  },

  // ==================== MARATHI (mr-IN) ====================
  {
    screenId: "S-0.0.5",
    variant: 1,
    trigger: "on_screen_load",
    text: "आम्हाला तुमचे लोकेशन हवे आहे.",
    romanTransliteration: "Amhala tumche location have ahe.",
    englishMeaning: "We need your location.",
    language: "mr-IN",
    speaker: "priya",
    pace: 0.86,
    pauseAfterMs: 1200,
    maxDurationS: 8,
    emotionalTone: "reassuring",
  },
  {
    screenId: "S-0.0.5",
    variant: 2,
    trigger: "on_screen_load",
    text: "लोकेशनमुळे आम्ही चांगली सेवा देऊ शकतो.",
    romanTransliteration: "Locationmule amhi changli seva deu shakto.",
    englishMeaning: "Location helps us provide better service.",
    language: "mr-IN",
    speaker: "priya",
    pace: 0.86,
    pauseAfterMs: 1200,
    maxDurationS: 8,
    emotionalTone: "helpful_guide",
  },
  {
    screenId: "S-0.0.5",
    variant: 3,
    trigger: "on_screen_load",
    text: "हे सुरक्षित आहे. डेटा सुरक्षित ठेवतो.",
    romanTransliteration: "He surakshit ahe. Data surakshit thevto.",
    englishMeaning: "It's safe. We keep data secure.",
    language: "mr-IN",
    speaker: "priya",
    pace: 0.84,
    pauseAfterMs: 1200,
    maxDurationS: 8,
    emotionalTone: "reassuring",
  },
  {
    screenId: "S-0.0.5",
    variant: 4,
    trigger: "on_screen_load",
    text: "कृपया लोकेशन परवानगी द्या.",
    romanTransliteration: "Kripya location paravangi dya.",
    englishMeaning: "Please give location permission.",
    language: "mr-IN",
    speaker: "priya",
    pace: 0.88,
    pauseAfterMs: 1200,
    maxDurationS: 8,
    emotionalTone: "warm_respectful",
  },

  // ==================== GUJARATI (gu-IN) ====================
  {
    screenId: "S-0.0.5",
    variant: 1,
    trigger: "on_screen_load",
    text: "અમને તમારા લોકેશનની જરૂર છે.",
    romanTransliteration: "Amne tamara locationni jarur chhe.",
    englishMeaning: "We need your location.",
    language: "gu-IN",
    speaker: "priya",
    pace: 0.85,
    pauseAfterMs: 1200,
    maxDurationS: 8,
    emotionalTone: "reassuring",
  },
  {
    screenId: "S-0.0.5",
    variant: 2,
    trigger: "on_screen_load",
    text: "લોકેશનથી અમે સારી સેવા આપી શકીએ.",
    romanTransliteration: "Locationthi ame saari seva aapi shakiye.",
    englishMeaning: "Location helps us provide better service.",
    language: "gu-IN",
    speaker: "priya",
    pace: 0.85,
    pauseAfterMs: 1200,
    maxDurationS: 8,
    emotionalTone: "helpful_guide",
  },
  {
    screenId: "S-0.0.5",
    variant: 3,
    trigger: "on_screen_load",
    text: "આ સુરક્ષિત છે. ડેટા સુરક્ષિત રાખીએ.",
    romanTransliteration: "Aa surakshit chhe. Data surakshit rakhiye.",
    englishMeaning: "It's safe. We keep data secure.",
    language: "gu-IN",
    speaker: "priya",
    pace: 0.83,
    pauseAfterMs: 1200,
    maxDurationS: 8,
    emotionalTone: "reassuring",
  },
  {
    screenId: "S-0.0.5",
    variant: 4,
    trigger: "on_screen_load",
    text: "કૃપા કરીને લોકેશન પરવાનગી આપો.",
    romanTransliteration: "Kripa karine location paravangi aapo.",
    englishMeaning: "Please give location permission.",
    language: "gu-IN",
    speaker: "priya",
    pace: 0.87,
    pauseAfterMs: 1200,
    maxDurationS: 8,
    emotionalTone: "warm_respectful",
  },

  // ==================== KANNADA (kn-IN) ====================
  {
    screenId: "S-0.0.5",
    variant: 1,
    trigger: "on_screen_load",
    text: "ನಮಗೆ ನಿಮ್ಮ ಲೊಕೇಶನ್ ಅಗತ್ಯವಿದೆ.",
    romanTransliteration: "Namege nimma location avashyavide.",
    englishMeaning: "We need your location.",
    language: "kn-IN",
    speaker: "priya",
    pace: 0.84,
    pauseAfterMs: 1200,
    maxDurationS: 8,
    emotionalTone: "reassuring",
  },
  {
    screenId: "S-0.0.5",
    variant: 2,
    trigger: "on_screen_load",
    text: "ಲೊಕೇಶನ್ ಮೂಲಕ ನಾವು ಉತ್ತಮ ಸೇವೆ ನೀಡಬಹುದು.",
    romanTransliteration: "Location moolaka naavu uttama seve needabahudu.",
    englishMeaning: "Location helps us provide better service.",
    language: "kn-IN",
    speaker: "priya",
    pace: 0.84,
    pauseAfterMs: 1200,
    maxDurationS: 8,
    emotionalTone: "helpful_guide",
  },
  {
    screenId: "S-0.0.5",
    variant: 3,
    trigger: "on_screen_load",
    text: "ಇದು ಸುರಕ್ಷಿತ. ಡೇಟಾವನ್ನು ಸುರಕ್ಷಿತವಾಗಿಡಲಾಗುತ್ತದೆ.",
    romanTransliteration: "Idhu surakshita. Dataavanu surakshitavaagidalaguttade.",
    englishMeaning: "It's safe. Data is kept secure.",
    language: "kn-IN",
    speaker: "priya",
    pace: 0.82,
    pauseAfterMs: 1200,
    maxDurationS: 8,
    emotionalTone: "reassuring",
  },
  {
    screenId: "S-0.0.5",
    variant: 4,
    trigger: "on_screen_load",
    text: "ದಯವಿಟ್ಟು ಲೊಕೇಶನ್ ಅನುಮತಿ ನೀಡಿ.",
    romanTransliteration: "Dayavittu location anumati needi.",
    englishMeaning: "Please give location permission.",
    language: "kn-IN",
    speaker: "priya",
    pace: 0.86,
    pauseAfterMs: 1200,
    maxDurationS: 8,
    emotionalTone: "warm_respectful",
  },

  // ==================== MALAYALAM (ml-IN) ====================
  {
    screenId: "S-0.0.5",
    variant: 1,
    trigger: "on_screen_load",
    text: "ഞങ്ങൾക്ക് നിങ്ങളുടെ ലൊക്കേഷൻ ആവശ്യമാണ്.",
    romanTransliteration: "Ningalkku ningalude location aavashyamaanu.",
    englishMeaning: "We need your location.",
    language: "ml-IN",
    speaker: "priya",
    pace: 0.83,
    pauseAfterMs: 1200,
    maxDurationS: 8,
    emotionalTone: "reassuring",
  },
  {
    screenId: "S-0.0.5",
    variant: 2,
    trigger: "on_screen_load",
    text: "ലൊക്കേഷൻ വഴി മികച്ച സേവനം നൽകാം.",
    romanTransliteration: "Location vazhi mikacha sevanam nalkaam.",
    englishMeaning: "Location helps us provide better service.",
    language: "ml-IN",
    speaker: "priya",
    pace: 0.83,
    pauseAfterMs: 1200,
    maxDurationS: 8,
    emotionalTone: "helpful_guide",
  },
  {
    screenId: "S-0.0.5",
    variant: 3,
    trigger: "on_screen_load",
    text: "ഇത് സുരക്ഷിതമാണ്. ഡാറ്റ സുരക്ഷിതമായി സൂക്ഷിക്കും.",
    romanTransliteration: "Ithu surakshithamaanu. Data surakshithamaayi sookshikkum.",
    englishMeaning: "It's safe. Data will be kept secure.",
    language: "ml-IN",
    speaker: "priya",
    pace: 0.80,
    pauseAfterMs: 1200,
    maxDurationS: 8,
    emotionalTone: "reassuring",
  },
  {
    screenId: "S-0.0.5",
    variant: 4,
    trigger: "on_screen_load",
    text: "ദയവായി ലൊക്കേഷൻ അനുമതി നൽകുക.",
    romanTransliteration: "Dayavayi location anumathi nalkuka.",
    englishMeaning: "Please give location permission.",
    language: "ml-IN",
    speaker: "priya",
    pace: 0.85,
    pauseAfterMs: 1200,
    maxDurationS: 8,
    emotionalTone: "warm_respectful",
  },

  // ==================== PUNJABI (pa-IN) ====================
  {
    screenId: "S-0.0.5",
    variant: 1,
    trigger: "on_screen_load",
    text: "ਸਾਨੂੰ ਤੁਹਾਡੀ ਲੋਕੇਸ਼ਨ ਚਾਹੀਦੀ ਹੈ।",
    romanTransliteration: "Saanu tuhadi location chahidi hai.",
    englishMeaning: "We need your location.",
    language: "pa-IN",
    speaker: "priya",
    pace: 0.85,
    pauseAfterMs: 1200,
    maxDurationS: 8,
    emotionalTone: "reassuring",
  },
  {
    screenId: "S-0.0.5",
    variant: 2,
    trigger: "on_screen_load",
    text: "ਲੋਕੇਸ਼ਨ ਨਾਲ ਅਸੀਂ ਵਧੀਆ ਸੇਵਾ ਦੇ ਸਕਦੇ ਹਾਂ।",
    romanTransliteration: "Location naal asi vadiya seva de sakde haan.",
    englishMeaning: "Location helps us provide better service.",
    language: "pa-IN",
    speaker: "priya",
    pace: 0.85,
    pauseAfterMs: 1200,
    maxDurationS: 8,
    emotionalTone: "helpful_guide",
  },
  {
    screenId: "S-0.0.5",
    variant: 3,
    trigger: "on_screen_load",
    text: "ਇਹ ਸੁਰੱਖਿਅਤ ਹੈ। ਅਸੀਂ ਡੇਟਾ ਸੁਰੱਖਿਅਤ ਰੱਖਦੇ ਹਾਂ।",
    romanTransliteration: "Ih surakkhiat hai. Asi data surakkhiat rakhde haan.",
    englishMeaning: "It's safe. We keep data secure.",
    language: "pa-IN",
    speaker: "priya",
    pace: 0.83,
    pauseAfterMs: 1200,
    maxDurationS: 8,
    emotionalTone: "reassuring",
  },
  {
    screenId: "S-0.0.5",
    variant: 4,
    trigger: "on_screen_load",
    text: "ਕਿਰਪਾ ਕਰਕੇ ਲੋਕੇਸ਼ਨ ਇਜਾਜ਼ਤ ਦਿਓ।",
    romanTransliteration: "Kirpa karke location ijaazat dio.",
    englishMeaning: "Please give location permission.",
    language: "pa-IN",
    speaker: "priya",
    pace: 0.87,
    pauseAfterMs: 1200,
    maxDurationS: 8,
    emotionalTone: "warm_respectful",
  },

  // ==================== ODIA (or-IN) ====================
  {
    screenId: "S-0.0.5",
    variant: 1,
    trigger: "on_screen_load",
    text: "ଆମକୁ ଆପଣଙ୍କ ଲୋକେସନ୍ ଆବଶ୍ୟକ।",
    romanTransliteration: "Amaku aapanka location aabashyaka.",
    englishMeaning: "We need your location.",
    language: "or-IN",
    speaker: "priya",
    pace: 0.84,
    pauseAfterMs: 1200,
    maxDurationS: 8,
    emotionalTone: "reassuring",
  },
  {
    screenId: "S-0.0.5",
    variant: 2,
    trigger: "on_screen_load",
    text: "ଲୋକେସନ୍ ଦ୍ୱାରା ଆମେ ଭଲ ସେବା ଦେଇପାରିବା।",
    romanTransliteration: "Location dwara ame bhala seba deipariba.",
    englishMeaning: "Location helps us provide better service.",
    language: "or-IN",
    speaker: "priya",
    pace: 0.84,
    pauseAfterMs: 1200,
    maxDurationS: 8,
    emotionalTone: "helpful_guide",
  },
  {
    screenId: "S-0.0.5",
    variant: 3,
    trigger: "on_screen_load",
    text: "ଏହା ସୁରକ୍ଷିତ। ଆମେ ଡେଟା ସୁରକ୍ଷିତ ରଖୁ।",
    romanTransliteration: "Ehaa surakshita. Ame data surakshita rakhu.",
    englishMeaning: "It's safe. We keep data secure.",
    language: "or-IN",
    speaker: "priya",
    pace: 0.82,
    pauseAfterMs: 1200,
    maxDurationS: 8,
    emotionalTone: "reassuring",
  },
  {
    screenId: "S-0.0.5",
    variant: 4,
    trigger: "on_screen_load",
    text: "ଦୟାକରି ଲୋକେସନ୍ ଅନୁମତି ଦିଅନ୍ତୁ।",
    romanTransliteration: "Dayakari location anumati diantu.",
    englishMeaning: "Please give location permission.",
    language: "or-IN",
    speaker: "priya",
    pace: 0.86,
    pauseAfterMs: 1200,
    maxDurationS: 8,
    emotionalTone: "warm_respectful",
  },

  // ==================== ENGLISH (en-IN) ====================
  {
    screenId: "S-0.0.5",
    variant: 1,
    trigger: "on_screen_load",
    text: "We need your location.",
    romanTransliteration: "We need your location.",
    englishMeaning: "We need your location.",
    language: "en-IN",
    speaker: "priya",
    pace: 0.87,
    pauseAfterMs: 1200,
    maxDurationS: 8,
    emotionalTone: "reassuring",
  },
  {
    screenId: "S-0.0.5",
    variant: 2,
    trigger: "on_screen_load",
    text: "Location helps us serve you better.",
    romanTransliteration: "Location helps us serve you better.",
    englishMeaning: "Location helps us serve you better.",
    language: "en-IN",
    speaker: "priya",
    pace: 0.87,
    pauseAfterMs: 1200,
    maxDurationS: 8,
    emotionalTone: "helpful_guide",
  },
  {
    screenId: "S-0.0.5",
    variant: 3,
    trigger: "on_screen_load",
    text: "It's safe. We keep your data secure.",
    romanTransliteration: "It's safe. We keep your data secure.",
    englishMeaning: "It's safe. We keep your data secure.",
    language: "en-IN",
    speaker: "priya",
    pace: 0.85,
    pauseAfterMs: 1200,
    maxDurationS: 8,
    emotionalTone: "reassuring",
  },
  {
    screenId: "S-0.0.5",
    variant: 4,
    trigger: "on_screen_load",
    text: "Please allow location access.",
    romanTransliteration: "Please allow location access.",
    englishMeaning: "Please allow location access.",
    language: "en-IN",
    speaker: "priya",
    pace: 0.89,
    pauseAfterMs: 1200,
    maxDurationS: 8,
    emotionalTone: "warm_respectful",
  },

  // ==================== BHOJPURI (hi-IN fallback) ====================
  {
    screenId: "S-0.0.5",
    variant: 1,
    trigger: "on_screen_load",
    text: "हमका आपन लोकेशन चाहि।",
    romanTransliteration: "Hamka apna location chahi.",
    englishMeaning: "We need your location.",
    language: "hi-IN",
    speaker: "priya",
    pace: 0.85,
    pauseAfterMs: 1200,
    maxDurationS: 8,
    emotionalTone: "reassuring",
    fallback: true,
  },
  {
    screenId: "S-0.0.5",
    variant: 2,
    trigger: "on_screen_load",
    text: "लोकेशन से हमनी बेहतर सेवा देब।",
    romanTransliteration: "Location se hamni behtar seva deb.",
    englishMeaning: "Location helps us provide better service.",
    language: "hi-IN",
    speaker: "priya",
    pace: 0.85,
    pauseAfterMs: 1200,
    maxDurationS: 8,
    emotionalTone: "helpful_guide",
    fallback: true,
  },
  {
    screenId: "S-0.0.5",
    variant: 3,
    trigger: "on_screen_load",
    text: "ई सुरक्षित बा। डेटा के सुरक्षित रखीं।",
    romanTransliteration: "E surakshit ba. Data ke surakshit rakheen.",
    englishMeaning: "It's safe. We keep data secure.",
    language: "hi-IN",
    speaker: "priya",
    pace: 0.83,
    pauseAfterMs: 1200,
    maxDurationS: 8,
    emotionalTone: "reassuring",
    fallback: true,
  },
  {
    screenId: "S-0.0.5",
    variant: 4,
    trigger: "on_screen_load",
    text: "कृपया लोकेशन अनुमति दिहूँ।",
    romanTransliteration: "Kripya location anumati dihoon.",
    englishMeaning: "Please give location permission.",
    language: "hi-IN",
    speaker: "priya",
    pace: 0.87,
    pauseAfterMs: 1200,
    maxDurationS: 8,
    emotionalTone: "warm_respectful",
    fallback: true,
  },

  // ==================== MAITHILI (hi-IN fallback) ====================
  {
    screenId: "S-0.0.5",
    variant: 1,
    trigger: "on_screen_load",
    text: "हमरा सभकें अहाँक लोकेशन चाही।",
    romanTransliteration: "Hamra sabhaken aahank location chahi.",
    englishMeaning: "We need your location.",
    language: "hi-IN",
    speaker: "priya",
    pace: 0.85,
    pauseAfterMs: 1200,
    maxDurationS: 8,
    emotionalTone: "reassuring",
    fallback: true,
  },
  {
    screenId: "S-0.0.5",
    variant: 2,
    trigger: "on_screen_load",
    text: "लोकेशन सँ हमरा सभकें बेहतर सेवा देब।",
    romanTransliteration: "Location san hamra sabhaken behtar seva deb.",
    englishMeaning: "Location helps us provide better service.",
    language: "hi-IN",
    speaker: "priya",
    pace: 0.85,
    pauseAfterMs: 1200,
    maxDurationS: 8,
    emotionalTone: "helpful_guide",
    fallback: true,
  },
  {
    screenId: "S-0.0.5",
    variant: 3,
    trigger: "on_screen_load",
    text: "ई सुरक्षित अछि। डेटा केँ सुरक्षित रखैत छी।",
    romanTransliteration: "E surakshit achhi. Data ken surakshit rakheit chhi.",
    englishMeaning: "It's safe. We keep data secure.",
    language: "hi-IN",
    speaker: "priya",
    pace: 0.83,
    pauseAfterMs: 1200,
    maxDurationS: 8,
    emotionalTone: "reassuring",
    fallback: true,
  },
  {
    screenId: "S-0.0.5",
    variant: 4,
    trigger: "on_screen_load",
    text: "कृपया लोकेशन अनुमति दिअ।",
    romanTransliteration: "Kripya location anumati dia.",
    englishMeaning: "Please give location permission.",
    language: "hi-IN",
    speaker: "priya",
    pace: 0.87,
    pauseAfterMs: 1200,
    maxDurationS: 8,
    emotionalTone: "warm_respectful",
    fallback: true,
  },

  // ==================== SANSKRIT (hi-IN fallback) ====================
  {
    screenId: "S-0.0.5",
    variant: 1,
    trigger: "on_screen_load",
    text: "अस्माकं तव स्थानं आवश्यकम्।",
    romanTransliteration: "Asmaakan tava sthaanam aavashyakam.",
    englishMeaning: "We need your location.",
    language: "hi-IN",
    speaker: "priya",
    pace: 0.82,
    pauseAfterMs: 1200,
    maxDurationS: 8,
    emotionalTone: "reassuring",
    fallback: true,
  },
  {
    screenId: "S-0.0.5",
    variant: 2,
    trigger: "on_screen_load",
    text: "स्थानेन वयं उत्तमसेवां दातुं शक्नुमः।",
    romanTransliteration: "Sthaanena vayam uttamasevaam daatum shaknumah.",
    englishMeaning: "Location helps us provide better service.",
    language: "hi-IN",
    speaker: "priya",
    pace: 0.82,
    pauseAfterMs: 1200,
    maxDurationS: 8,
    emotionalTone: "helpful_guide",
    fallback: true,
  },
  {
    screenId: "S-0.0.5",
    variant: 3,
    trigger: "on_screen_load",
    text: "एतत् सुरक्षितम्। रक्षामः डेटा।",
    romanTransliteration: "Etat surakshitam. Rakshaamah data.",
    englishMeaning: "It's safe. We keep data secure.",
    language: "hi-IN",
    speaker: "priya",
    pace: 0.80,
    pauseAfterMs: 1200,
    maxDurationS: 8,
    emotionalTone: "reassuring",
    fallback: true,
  },
  {
    screenId: "S-0.0.5",
    variant: 4,
    trigger: "on_screen_load",
    text: "कृपया स्थानानुमतिं ददतु।",
    romanTransliteration: "Kripya sthaanaanumalim dadatu.",
    englishMeaning: "Please give location permission.",
    language: "hi-IN",
    speaker: "priya",
    pace: 0.84,
    pauseAfterMs: 1200,
    maxDurationS: 8,
    emotionalTone: "warm_respectful",
    fallback: true,
  },

  // ==================== ASSAMESE (hi-IN fallback) ====================
  {
    screenId: "S-0.0.5",
    variant: 1,
    trigger: "on_screen_load",
    text: "আমাক আপোনাৰ লোকেশ্যনৰ প্ৰয়োজন।",
    romanTransliteration: "Amak apunar locationor proyojon.",
    englishMeaning: "We need your location.",
    language: "hi-IN",
    speaker: "priya",
    pace: 0.84,
    pauseAfterMs: 1200,
    maxDurationS: 8,
    emotionalTone: "reassuring",
    fallback: true,
  },
  {
    screenId: "S-0.0.5",
    variant: 2,
    trigger: "on_screen_load",
    text: "লোকেশ্যনেৰে আমি উন্নত সেৱা দিব পাৰোঁ।",
    romanTransliteration: "Locationere ami unnato seva dib paaro.",
    englishMeaning: "Location helps us provide better service.",
    language: "hi-IN",
    speaker: "priya",
    pace: 0.84,
    pauseAfterMs: 1200,
    maxDurationS: 8,
    emotionalTone: "helpful_guide",
    fallback: true,
  },
  {
    screenId: "S-0.0.5",
    variant: 3,
    trigger: "on_screen_load",
    text: "ই নিৰাপদ। আমি ডেটা নিৰাপদ ৰাখোঁ।",
    romanTransliteration: "I nirapodo. Ami data nirapodo rakho.",
    englishMeaning: "It's safe. We keep data secure.",
    language: "hi-IN",
    speaker: "priya",
    pace: 0.82,
    pauseAfterMs: 1200,
    maxDurationS: 8,
    emotionalTone: "reassuring",
    fallback: true,
  },
  {
    screenId: "S-0.0.5",
    variant: 4,
    trigger: "on_screen_load",
    text: "অনুগ্ৰহ কৰি লোকেশ্যনৰ অনুমতি দিয়ক।",
    romanTransliteration: "Anugraha kori locationor anumati diyok.",
    englishMeaning: "Please give location permission.",
    language: "hi-IN",
    speaker: "priya",
    pace: 0.86,
    pauseAfterMs: 1200,
    maxDurationS: 8,
    emotionalTone: "warm_respectful",
    fallback: true,
  },
];

export default S0_0_5_PERMISSION_EXPLANATION;
