/**
 * S-0.0.6: Celebration/Success Screen Scripts
 * Screen: Celebrate successful setup completion
 * Total: 75 scripts (15 languages × 5 variants)
 * Note: Celebration screen has 5 language variants for extra joy!
 */

export const S0_0_6_CELEBRATION = [
  // ==================== HINDI (hi-IN) ====================
  {
    screenId: "S-0.0.6",
    variant: 1,
    trigger: "on_screen_load",
    text: "बहुत बढ़िया! सेटअप पूरा हुआ।",
    romanTransliteration: "Bahut badhiya! Setup poora hua.",
    englishMeaning: "Excellent! Setup complete.",
    language: "hi-IN",
    speaker: "priya",
    pace: 0.93,
    pauseAfterMs: 800,
    maxDurationS: 6,
    emotionalTone: "celebratory",
  },
  {
    screenId: "S-0.0.6",
    variant: 2,
    trigger: "on_screen_load",
    text: "शाबाश! आप तैयार हैं।",
    romanTransliteration: "Shabaash! Aap taiyaar hain.",
    englishMeaning: "Well done! You are ready.",
    language: "hi-IN",
    speaker: "priya",
    pace: 0.93,
    pauseAfterMs: 800,
    maxDurationS: 6,
    emotionalTone: "celebratory",
  },
  {
    screenId: "S-0.0.6",
    variant: 3,
    trigger: "on_screen_load",
    text: "धन्यवाद! स्वागत है।",
    romanTransliteration: "Dhanyavaad! Swaagat hai.",
    englishMeaning: "Thank you! Welcome.",
    language: "hi-IN",
    speaker: "priya",
    pace: 0.92,
    pauseAfterMs: 800,
    maxDurationS: 6,
    emotionalTone: "celebratory",
  },
  {
    screenId: "S-0.0.6",
    variant: 4,
    trigger: "on_screen_load",
    text: "सफल! अब शुरू करें।",
    romanTransliteration: "Safal! Ab shuru karein.",
    englishMeaning: "Success! Now let's begin.",
    language: "hi-IN",
    speaker: "priya",
    pace: 0.94,
    pauseAfterMs: 800,
    maxDurationS: 6,
    emotionalTone: "celebratory",
  },
  {
    screenId: "S-0.0.6",
    variant: 5,
    trigger: "on_screen_load",
    text: "वाह! सब कुछ तैयार है।",
    romanTransliteration: "Waah! Sab kuch taiyaar hai.",
    englishMeaning: "Wow! Everything is ready.",
    language: "hi-IN",
    speaker: "priya",
    pace: 0.95,
    pauseAfterMs: 800,
    maxDurationS: 6,
    emotionalTone: "celebratory",
  },

  // ==================== TAMIL (ta-IN) ====================
  {
    screenId: "S-0.0.6",
    variant: 1,
    trigger: "on_screen_load",
    text: "மிகவும் நன்று! அமைப்பு முடிந்தது.",
    romanTransliteration: "Migavum nandru! Amaippu mudindhadhu.",
    englishMeaning: "Excellent! Setup complete.",
    language: "ta-IN",
    speaker: "priya",
    pace: 0.91,
    pauseAfterMs: 800,
    maxDurationS: 6,
    emotionalTone: "celebratory",
  },
  {
    screenId: "S-0.0.6",
    variant: 2,
    trigger: "on_screen_load",
    text: "நன்றாக இருக்கிறது! நீங்கள் தயார்.",
    romanTransliteration: "Nandraaga irukkiradhu! Neengal thaayaar.",
    englishMeaning: "Well done! You are ready.",
    language: "ta-IN",
    speaker: "priya",
    pace: 0.91,
    pauseAfterMs: 800,
    maxDurationS: 6,
    emotionalTone: "celebratory",
  },
  {
    screenId: "S-0.0.6",
    variant: 3,
    trigger: "on_screen_load",
    text: "நன்றி! வரவேற்கிறோம்.",
    romanTransliteration: "Nandri! Varaverkirom.",
    englishMeaning: "Thank you! Welcome.",
    language: "ta-IN",
    speaker: "priya",
    pace: 0.90,
    pauseAfterMs: 800,
    maxDurationS: 6,
    emotionalTone: "celebratory",
  },
  {
    screenId: "S-0.0.6",
    variant: 4,
    trigger: "on_screen_load",
    text: "வெற்றி! இப்போது தொடங்கலாம்.",
    romanTransliteration: "Vetri! Ippodhu thodangalam.",
    englishMeaning: "Success! Now let's begin.",
    language: "ta-IN",
    speaker: "priya",
    pace: 0.92,
    pauseAfterMs: 800,
    maxDurationS: 6,
    emotionalTone: "celebratory",
  },
  {
    screenId: "S-0.0.6",
    variant: 5,
    trigger: "on_screen_load",
    text: "அருமை! எல்லாம் தயார்.",
    romanTransliteration: "Arumai! Ellaam thaayaar.",
    englishMeaning: "Wow! Everything is ready.",
    language: "ta-IN",
    speaker: "priya",
    pace: 0.93,
    pauseAfterMs: 800,
    maxDurationS: 6,
    emotionalTone: "celebratory",
  },

  // ==================== TELUGU (te-IN) ====================
  {
    screenId: "S-0.0.6",
    variant: 1,
    trigger: "on_screen_load",
    text: "చాలా బాగుంది! సెటప్ పూర్తయింది.",
    romanTransliteration: "Chaala baagundi! Setup poorthayindi.",
    englishMeaning: "Excellent! Setup complete.",
    language: "te-IN",
    speaker: "priya",
    pace: 0.92,
    pauseAfterMs: 800,
    maxDurationS: 6,
    emotionalTone: "celebratory",
  },
  {
    screenId: "S-0.0.6",
    variant: 2,
    trigger: "on_screen_load",
    text: "బాగుంది! మీరు సిద్ధంగా ఉన్నారు.",
    romanTransliteration: "Baagundi! Meeru siddhanga unnaru.",
    englishMeaning: "Well done! You are ready.",
    language: "te-IN",
    speaker: "priya",
    pace: 0.92,
    pauseAfterMs: 800,
    maxDurationS: 6,
    emotionalTone: "celebratory",
  },
  {
    screenId: "S-0.0.6",
    variant: 3,
    trigger: "on_screen_load",
    text: "ధన్యవాదాలు! స్వాగతం.",
    romanTransliteration: "Dhanyavaadaalu! Swaagatham.",
    englishMeaning: "Thank you! Welcome.",
    language: "te-IN",
    speaker: "priya",
    pace: 0.91,
    pauseAfterMs: 800,
    maxDurationS: 6,
    emotionalTone: "celebratory",
  },
  {
    screenId: "S-0.0.6",
    variant: 4,
    trigger: "on_screen_load",
    text: "విజయం! ఇప్పుడు ప్రారంభిద్దాం.",
    romanTransliteration: "Vijayam! Ippudu prarambhiddam.",
    englishMeaning: "Success! Now let's begin.",
    language: "te-IN",
    speaker: "priya",
    pace: 0.93,
    pauseAfterMs: 800,
    maxDurationS: 6,
    emotionalTone: "celebratory",
  },
  {
    screenId: "S-0.0.6",
    variant: 5,
    trigger: "on_screen_load",
    text: "వావ్! అన్నీ సిద్ధం.",
    romanTransliteration: "Vaav! Anni siddham.",
    englishMeaning: "Wow! Everything is ready.",
    language: "te-IN",
    speaker: "priya",
    pace: 0.94,
    pauseAfterMs: 800,
    maxDurationS: 6,
    emotionalTone: "celebratory",
  },

  // ==================== BENGALI (bn-IN) ====================
  {
    screenId: "S-0.0.6",
    variant: 1,
    trigger: "on_screen_load",
    text: "খুব ভালো! সেটআপ সম্পূর্ণ।",
    romanTransliteration: "Khub bhalo! Setup sompurno.",
    englishMeaning: "Excellent! Setup complete.",
    language: "bn-IN",
    speaker: "priya",
    pace: 0.92,
    pauseAfterMs: 800,
    maxDurationS: 6,
    emotionalTone: "celebratory",
  },
  {
    screenId: "S-0.0.6",
    variant: 2,
    trigger: "on_screen_load",
    text: "দারুণ! আপনি তৈরি।",
    romanTransliteration: "Darun! Aapni toiri.",
    englishMeaning: "Well done! You are ready.",
    language: "bn-IN",
    speaker: "priya",
    pace: 0.92,
    pauseAfterMs: 800,
    maxDurationS: 6,
    emotionalTone: "celebratory",
  },
  {
    screenId: "S-0.0.6",
    variant: 3,
    trigger: "on_screen_load",
    text: "ধন্যবাদ! স্বাগতম।",
    romanTransliteration: "Dhonnobad! Swagotom.",
    englishMeaning: "Thank you! Welcome.",
    language: "bn-IN",
    speaker: "priya",
    pace: 0.91,
    pauseAfterMs: 800,
    maxDurationS: 6,
    emotionalTone: "celebratory",
  },
  {
    screenId: "S-0.0.6",
    variant: 4,
    trigger: "on_screen_load",
    text: "সফল! এবার শুরু করা যাক।",
    romanTransliteration: "Sofol! Ebar shuru kora jak.",
    englishMeaning: "Success! Now let's begin.",
    language: "bn-IN",
    speaker: "priya",
    pace: 0.93,
    pauseAfterMs: 800,
    maxDurationS: 6,
    emotionalTone: "celebratory",
  },
  {
    screenId: "S-0.0.6",
    variant: 5,
    trigger: "on_screen_load",
    text: "বাহ! সব কিছু তৈরি।",
    romanTransliteration: "Baah! Shob kichu toiri.",
    englishMeaning: "Wow! Everything is ready.",
    language: "bn-IN",
    speaker: "priya",
    pace: 0.94,
    pauseAfterMs: 800,
    maxDurationS: 6,
    emotionalTone: "celebratory",
  },

  // ==================== MARATHI (mr-IN) ====================
  {
    screenId: "S-0.0.6",
    variant: 1,
    trigger: "on_screen_load",
    text: "खूप छान! सेटअप पूर्ण झाले.",
    romanTransliteration: "Khoop chhan! Setup poorna zhaale.",
    englishMeaning: "Excellent! Setup complete.",
    language: "mr-IN",
    speaker: "priya",
    pace: 0.93,
    pauseAfterMs: 800,
    maxDurationS: 6,
    emotionalTone: "celebratory",
  },
  {
    screenId: "S-0.0.6",
    variant: 2,
    trigger: "on_screen_load",
    text: "वाहवा! तुम्ही तयार आहात.",
    romanTransliteration: "Vaahava! Tumhi tayaar aahaat.",
    englishMeaning: "Well done! You are ready.",
    language: "mr-IN",
    speaker: "priya",
    pace: 0.93,
    pauseAfterMs: 800,
    maxDurationS: 6,
    emotionalTone: "celebratory",
  },
  {
    screenId: "S-0.0.6",
    variant: 3,
    trigger: "on_screen_load",
    text: "आभार! स्वागत आहे.",
    romanTransliteration: "Aabhaar! Swaagat ahe.",
    englishMeaning: "Thank you! Welcome.",
    language: "mr-IN",
    speaker: "priya",
    pace: 0.92,
    pauseAfterMs: 800,
    maxDurationS: 6,
    emotionalTone: "celebratory",
  },
  {
    screenId: "S-0.0.6",
    variant: 4,
    trigger: "on_screen_load",
    text: "यशस्वी! आता सुरुवात करूया.",
    romanTransliteration: "Yashasvi! Aata suruvaat karuyaa.",
    englishMeaning: "Success! Now let's begin.",
    language: "mr-IN",
    speaker: "priya",
    pace: 0.94,
    pauseAfterMs: 800,
    maxDurationS: 6,
    emotionalTone: "celebratory",
  },
  {
    screenId: "S-0.0.6",
    variant: 5,
    trigger: "on_screen_load",
    text: "वाह! सगळं तयार आहे.",
    romanTransliteration: "Vaah! Sagalam tayaar ahe.",
    englishMeaning: "Wow! Everything is ready.",
    language: "mr-IN",
    speaker: "priya",
    pace: 0.95,
    pauseAfterMs: 800,
    maxDurationS: 6,
    emotionalTone: "celebratory",
  },

  // ==================== GUJARATI (gu-IN) ====================
  {
    screenId: "S-0.0.6",
    variant: 1,
    trigger: "on_screen_load",
    text: "ખૂબ સારું! સેટઅપ પૂર્ણ થયું.",
    romanTransliteration: "Khub saaru! Setup poorna thayu.",
    englishMeaning: "Excellent! Setup complete.",
    language: "gu-IN",
    speaker: "priya",
    pace: 0.92,
    pauseAfterMs: 800,
    maxDurationS: 6,
    emotionalTone: "celebratory",
  },
  {
    screenId: "S-0.0.6",
    variant: 2,
    trigger: "on_screen_load",
    text: "સરસ! તમે તૈયાર છો.",
    romanTransliteration: "Saras! Tame taiyaar cho.",
    englishMeaning: "Well done! You are ready.",
    language: "gu-IN",
    speaker: "priya",
    pace: 0.92,
    pauseAfterMs: 800,
    maxDurationS: 6,
    emotionalTone: "celebratory",
  },
  {
    screenId: "S-0.0.6",
    variant: 3,
    trigger: "on_screen_load",
    text: "આભાર! સ્વાગત છે.",
    romanTransliteration: "Aabhaar! Swaagat chhe.",
    englishMeaning: "Thank you! Welcome.",
    language: "gu-IN",
    speaker: "priya",
    pace: 0.91,
    pauseAfterMs: 800,
    maxDurationS: 6,
    emotionalTone: "celebratory",
  },
  {
    screenId: "S-0.0.6",
    variant: 4,
    trigger: "on_screen_load",
    text: "સફળ! હવે શરૂ કરીએ.",
    romanTransliteration: "Safal! Have shuru kariye.",
    englishMeaning: "Success! Now let's begin.",
    language: "gu-IN",
    speaker: "priya",
    pace: 0.93,
    pauseAfterMs: 800,
    maxDurationS: 6,
    emotionalTone: "celebratory",
  },
  {
    screenId: "S-0.0.6",
    variant: 5,
    trigger: "on_screen_load",
    text: "વાહ! બધું તૈયાર છે.",
    romanTransliteration: "Vaah! Badhu taiyaar chhe.",
    englishMeaning: "Wow! Everything is ready.",
    language: "gu-IN",
    speaker: "priya",
    pace: 0.94,
    pauseAfterMs: 800,
    maxDurationS: 6,
    emotionalTone: "celebratory",
  },

  // ==================== KANNADA (kn-IN) ====================
  {
    screenId: "S-0.0.6",
    variant: 1,
    trigger: "on_screen_load",
    text: "ತುಂಬಾ ಚೆನ್ನಾಗಿದೆ! ಸೆಟಪ್ ಪೂರ್ಣಗೊಂಡಿದೆ.",
    romanTransliteration: "Tumba chennaagide! Setup poornagondide.",
    englishMeaning: "Excellent! Setup complete.",
    language: "kn-IN",
    speaker: "priya",
    pace: 0.92,
    pauseAfterMs: 800,
    maxDurationS: 6,
    emotionalTone: "celebratory",
  },
  {
    screenId: "S-0.0.6",
    variant: 2,
    trigger: "on_screen_load",
    text: "ಉತ್ತಮ! ನೀವು ಸಿದ್ಧರಿದ್ದೀರಿ.",
    romanTransliteration: "Uttama! Neevu siddhariddiri.",
    englishMeaning: "Well done! You are ready.",
    language: "kn-IN",
    speaker: "priya",
    pace: 0.92,
    pauseAfterMs: 800,
    maxDurationS: 6,
    emotionalTone: "celebratory",
  },
  {
    screenId: "S-0.0.6",
    variant: 3,
    trigger: "on_screen_load",
    text: "ಧನ್ಯವಾದಗಳು! ಸ್ವಾಗತ.",
    romanTransliteration: "Dhanyavaadagalu! Swaagata.",
    englishMeaning: "Thank you! Welcome.",
    language: "kn-IN",
    speaker: "priya",
    pace: 0.91,
    pauseAfterMs: 800,
    maxDurationS: 6,
    emotionalTone: "celebratory",
  },
  {
    screenId: "S-0.0.6",
    variant: 4,
    trigger: "on_screen_load",
    text: "ಯಶಸ್ವಿ! ಈಗ ಪ್ರಾರಂಭಿಸೋಣ.",
    romanTransliteration: "Yashasvi! Eega prarambhisona.",
    englishMeaning: "Success! Now let's begin.",
    language: "kn-IN",
    speaker: "priya",
    pace: 0.93,
    pauseAfterMs: 800,
    maxDurationS: 6,
    emotionalTone: "celebratory",
  },
  {
    screenId: "S-0.0.6",
    variant: 5,
    trigger: "on_screen_load",
    text: "ವಾವ್! ಎಲ್ಲಾ ಸಿದ್ಧವಿದೆ.",
    romanTransliteration: "Vaav! Ellaa siddhavide.",
    englishMeaning: "Wow! Everything is ready.",
    language: "kn-IN",
    speaker: "priya",
    pace: 0.94,
    pauseAfterMs: 800,
    maxDurationS: 6,
    emotionalTone: "celebratory",
  },

  // ==================== MALAYALAM (ml-IN) ====================
  {
    screenId: "S-0.0.6",
    variant: 1,
    trigger: "on_screen_load",
    text: "വളരെ നല്ലത്! സെറ്റപ്പ് പൂർത്തിയായി.",
    romanTransliteration: "Valare nallathu! Setup poorthiyaayi.",
    englishMeaning: "Excellent! Setup complete.",
    language: "ml-IN",
    speaker: "priya",
    pace: 0.91,
    pauseAfterMs: 800,
    maxDurationS: 6,
    emotionalTone: "celebratory",
  },
  {
    screenId: "S-0.0.6",
    variant: 2,
    trigger: "on_screen_load",
    text: "നന്നായി! നിങ്ങൾ തയ്യാറാണ്.",
    romanTransliteration: "Nannaayi! Ningal thayaaraanu.",
    englishMeaning: "Well done! You are ready.",
    language: "ml-IN",
    speaker: "priya",
    pace: 0.91,
    pauseAfterMs: 800,
    maxDurationS: 6,
    emotionalTone: "celebratory",
  },
  {
    screenId: "S-0.0.6",
    variant: 3,
    trigger: "on_screen_load",
    text: "നന്ദി! സ്വാഗതം.",
    romanTransliteration: "Nandi! Swaagatham.",
    englishMeaning: "Thank you! Welcome.",
    language: "ml-IN",
    speaker: "priya",
    pace: 0.90,
    pauseAfterMs: 800,
    maxDurationS: 6,
    emotionalTone: "celebratory",
  },
  {
    screenId: "S-0.0.6",
    variant: 4,
    trigger: "on_screen_load",
    text: "വിജയം! ഇനി തുടങ്ങാം.",
    romanTransliteration: "Vijayam! Ini thudangaam.",
    englishMeaning: "Success! Now let's begin.",
    language: "ml-IN",
    speaker: "priya",
    pace: 0.92,
    pauseAfterMs: 800,
    maxDurationS: 6,
    emotionalTone: "celebratory",
  },
  {
    screenId: "S-0.0.6",
    variant: 5,
    trigger: "on_screen_load",
    text: "വാവ്! എല്ലാം തയ്യാർ.",
    romanTransliteration: "Vaav! Ellaam thayaar.",
    englishMeaning: "Wow! Everything is ready.",
    language: "ml-IN",
    speaker: "priya",
    pace: 0.93,
    pauseAfterMs: 800,
    maxDurationS: 6,
    emotionalTone: "celebratory",
  },

  // ==================== PUNJABI (pa-IN) ====================
  {
    screenId: "S-0.0.6",
    variant: 1,
    trigger: "on_screen_load",
    text: "ਬਹੁਤ ਵਧੀਆ! ਸੈਟਅਪ ਪੂਰਾ ਹੋਇਆ।",
    romanTransliteration: "Bahut vadiya! Setup poora hoya.",
    englishMeaning: "Excellent! Setup complete.",
    language: "pa-IN",
    speaker: "priya",
    pace: 0.92,
    pauseAfterMs: 800,
    maxDurationS: 6,
    emotionalTone: "celebratory",
  },
  {
    screenId: "S-0.0.6",
    variant: 2,
    trigger: "on_screen_load",
    text: "ਵਾਹਵਾ! ਤੁਸੀਂ ਤਿਆਰ ਹੋ।",
    romanTransliteration: "Vaahava! Tusī taiyaar ho.",
    englishMeaning: "Well done! You are ready.",
    language: "pa-IN",
    speaker: "priya",
    pace: 0.92,
    pauseAfterMs: 800,
    maxDurationS: 6,
    emotionalTone: "celebratory",
  },
  {
    screenId: "S-0.0.6",
    variant: 3,
    trigger: "on_screen_load",
    text: "ਧੰਨਵਾਦ! ਸਵਾਗਤ ਹੈ।",
    romanTransliteration: "Dhannavaad! Swaagat hai.",
    englishMeaning: "Thank you! Welcome.",
    language: "pa-IN",
    speaker: "priya",
    pace: 0.91,
    pauseAfterMs: 800,
    maxDurationS: 6,
    emotionalTone: "celebratory",
  },
  {
    screenId: "S-0.0.6",
    variant: 4,
    trigger: "on_screen_load",
    text: "ਸਫਲਤਾ! ਹੁਣ ਸ਼ੁਰੂ ਕਰਦੇ ਹਾਂ।",
    romanTransliteration: "Safalta! Hun shuru karde haan.",
    englishMeaning: "Success! Now let's begin.",
    language: "pa-IN",
    speaker: "priya",
    pace: 0.93,
    pauseAfterMs: 800,
    maxDurationS: 6,
    emotionalTone: "celebratory",
  },
  {
    screenId: "S-0.0.6",
    variant: 5,
    trigger: "on_screen_load",
    text: "ਵਾਹ! ਸਭ ਕੁਝ ਤਿਆਰ ਹੈ।",
    romanTransliteration: "Vaah! Sabh kujh taiyaar hai.",
    englishMeaning: "Wow! Everything is ready.",
    language: "pa-IN",
    speaker: "priya",
    pace: 0.94,
    pauseAfterMs: 800,
    maxDurationS: 6,
    emotionalTone: "celebratory",
  },

  // ==================== ODIA (or-IN) ====================
  {
    screenId: "S-0.0.6",
    variant: 1,
    trigger: "on_screen_load",
    text: "ଖୁବ୍ ଭଲ! ସେଟଅପ୍ ସମ୍ପୂର୍ଣ୍ଣ ହେଲା।",
    romanTransliteration: "Khub bhala! Setup sampurna hela.",
    englishMeaning: "Excellent! Setup complete.",
    language: "or-IN",
    speaker: "priya",
    pace: 0.92,
    pauseAfterMs: 800,
    maxDurationS: 6,
    emotionalTone: "celebratory",
  },
  {
    screenId: "S-0.0.6",
    variant: 2,
    trigger: "on_screen_load",
    text: "ବାହା! ଆପଣ ତିଆରି ଅଛନ୍ତି।",
    romanTransliteration: "Baaha! Aapan tiaari achhanti.",
    englishMeaning: "Well done! You are ready.",
    language: "or-IN",
    speaker: "priya",
    pace: 0.92,
    pauseAfterMs: 800,
    maxDurationS: 6,
    emotionalTone: "celebratory",
  },
  {
    screenId: "S-0.0.6",
    variant: 3,
    trigger: "on_screen_load",
    text: "ଧନ୍ୟବାଦ! ସ୍ୱାଗତ।",
    romanTransliteration: "Dhanyabaada! Swaagata.",
    englishMeaning: "Thank you! Welcome.",
    language: "or-IN",
    speaker: "priya",
    pace: 0.91,
    pauseAfterMs: 800,
    maxDurationS: 6,
    emotionalTone: "celebratory",
  },
  {
    screenId: "S-0.0.6",
    variant: 4,
    trigger: "on_screen_load",
    text: "ସଫଳ! ଏବେ ଆରମ୍ଭ କରିବା।",
    romanTransliteration: "Safala! Ebe arambha kariba.",
    englishMeaning: "Success! Now let's begin.",
    language: "or-IN",
    speaker: "priya",
    pace: 0.93,
    pauseAfterMs: 800,
    maxDurationS: 6,
    emotionalTone: "celebratory",
  },
  {
    screenId: "S-0.0.6",
    variant: 5,
    trigger: "on_screen_load",
    text: "ବାଃ! ସବୁକିଛି ତିଆରି ଅଛି।",
    romanTransliteration: "Baa! Sabukichi tiaari achhi.",
    englishMeaning: "Wow! Everything is ready.",
    language: "or-IN",
    speaker: "priya",
    pace: 0.94,
    pauseAfterMs: 800,
    maxDurationS: 6,
    emotionalTone: "celebratory",
  },

  // ==================== ENGLISH (en-IN) ====================
  {
    screenId: "S-0.0.6",
    variant: 1,
    trigger: "on_screen_load",
    text: "Excellent! Setup complete.",
    romanTransliteration: "Excellent! Setup complete.",
    englishMeaning: "Excellent! Setup complete.",
    language: "en-IN",
    speaker: "priya",
    pace: 0.94,
    pauseAfterMs: 800,
    maxDurationS: 6,
    emotionalTone: "celebratory",
  },
  {
    screenId: "S-0.0.6",
    variant: 2,
    trigger: "on_screen_load",
    text: "Well done! You are ready.",
    romanTransliteration: "Well done! You are ready.",
    englishMeaning: "Well done! You are ready.",
    language: "en-IN",
    speaker: "priya",
    pace: 0.94,
    pauseAfterMs: 800,
    maxDurationS: 6,
    emotionalTone: "celebratory",
  },
  {
    screenId: "S-0.0.6",
    variant: 3,
    trigger: "on_screen_load",
    text: "Thank you! Welcome aboard.",
    romanTransliteration: "Thank you! Welcome aboard.",
    englishMeaning: "Thank you! Welcome aboard.",
    language: "en-IN",
    speaker: "priya",
    pace: 0.93,
    pauseAfterMs: 800,
    maxDurationS: 6,
    emotionalTone: "celebratory",
  },
  {
    screenId: "S-0.0.6",
    variant: 4,
    trigger: "on_screen_load",
    text: "Success! Let's get started.",
    romanTransliteration: "Success! Let's get started.",
    englishMeaning: "Success! Let's get started.",
    language: "en-IN",
    speaker: "priya",
    pace: 0.95,
    pauseAfterMs: 800,
    maxDurationS: 6,
    emotionalTone: "celebratory",
  },
  {
    screenId: "S-0.0.6",
    variant: 5,
    trigger: "on_screen_load",
    text: "Wow! All set and ready.",
    romanTransliteration: "Wow! All set and ready.",
    englishMeaning: "Wow! All set and ready.",
    language: "en-IN",
    speaker: "priya",
    pace: 0.95,
    pauseAfterMs: 800,
    maxDurationS: 6,
    emotionalTone: "celebratory",
  },

  // ==================== BHOJPURI (hi-IN fallback) ====================
  {
    screenId: "S-0.0.6",
    variant: 1,
    trigger: "on_screen_load",
    text: "बहुत बढ़िया! सेटअप पूरा भइल।",
    romanTransliteration: "Bahut badhiya! Setup poora bhail.",
    englishMeaning: "Excellent! Setup complete.",
    language: "hi-IN",
    speaker: "priya",
    pace: 0.93,
    pauseAfterMs: 800,
    maxDurationS: 6,
    emotionalTone: "celebratory",
    fallback: true,
  },
  {
    screenId: "S-0.0.6",
    variant: 2,
    trigger: "on_screen_load",
    text: "वाहवा! तैयार बानी।",
    romanTransliteration: "Vaahava! Taiyaar bani.",
    englishMeaning: "Well done! You are ready.",
    language: "hi-IN",
    speaker: "priya",
    pace: 0.93,
    pauseAfterMs: 800,
    maxDurationS: 6,
    emotionalTone: "celebratory",
    fallback: true,
  },
  {
    screenId: "S-0.0.6",
    variant: 3,
    trigger: "on_screen_load",
    text: "धन्यवाद! स्वागत बा।",
    romanTransliteration: "Dhanyavaad! Swaagat ba.",
    englishMeaning: "Thank you! Welcome.",
    language: "hi-IN",
    speaker: "priya",
    pace: 0.92,
    pauseAfterMs: 800,
    maxDurationS: 6,
    emotionalTone: "celebratory",
    fallback: true,
  },
  {
    screenId: "S-0.0.6",
    variant: 4,
    trigger: "on_screen_load",
    text: "सफल! अब सुरु करीं।",
    romanTransliteration: "Safal! Ab suru kareen.",
    englishMeaning: "Success! Now let's begin.",
    language: "hi-IN",
    speaker: "priya",
    pace: 0.94,
    pauseAfterMs: 800,
    maxDurationS: 6,
    emotionalTone: "celebratory",
    fallback: true,
  },
  {
    screenId: "S-0.0.6",
    variant: 5,
    trigger: "on_screen_load",
    text: "वाह! सब तैयार बा।",
    romanTransliteration: "Vaah! Sab taiyaar ba.",
    englishMeaning: "Wow! Everything is ready.",
    language: "hi-IN",
    speaker: "priya",
    pace: 0.95,
    pauseAfterMs: 800,
    maxDurationS: 6,
    emotionalTone: "celebratory",
    fallback: true,
  },

  // ==================== MAITHILI (hi-IN fallback) ====================
  {
    screenId: "S-0.0.6",
    variant: 1,
    trigger: "on_screen_load",
    text: "बहुत बढ़िया! सेटअप पूरा भेल।",
    romanTransliteration: "Bahut badhiya! Setup poora bhel.",
    englishMeaning: "Excellent! Setup complete.",
    language: "hi-IN",
    speaker: "priya",
    pace: 0.93,
    pauseAfterMs: 800,
    maxDurationS: 6,
    emotionalTone: "celebratory",
    fallback: true,
  },
  {
    screenId: "S-0.0.6",
    variant: 2,
    trigger: "on_screen_load",
    text: "वाहवा! तैयार छी।",
    romanTransliteration: "Vaahava! Taiyaar chhi.",
    englishMeaning: "Well done! You are ready.",
    language: "hi-IN",
    speaker: "priya",
    pace: 0.93,
    pauseAfterMs: 800,
    maxDurationS: 6,
    emotionalTone: "celebratory",
    fallback: true,
  },
  {
    screenId: "S-0.0.6",
    variant: 3,
    trigger: "on_screen_load",
    text: "धन्यवाद! स्वागत अछि।",
    romanTransliteration: "Dhanyavaad! Swaagat achhi.",
    englishMeaning: "Thank you! Welcome.",
    language: "hi-IN",
    speaker: "priya",
    pace: 0.92,
    pauseAfterMs: 800,
    maxDurationS: 6,
    emotionalTone: "celebratory",
    fallback: true,
  },
  {
    screenId: "S-0.0.6",
    variant: 4,
    trigger: "on_screen_load",
    text: "सफल! आब शुरू करी।",
    romanTransliteration: "Safal! Aab shuru kari.",
    englishMeaning: "Success! Now let's begin.",
    language: "hi-IN",
    speaker: "priya",
    pace: 0.94,
    pauseAfterMs: 800,
    maxDurationS: 6,
    emotionalTone: "celebratory",
    fallback: true,
  },
  {
    screenId: "S-0.0.6",
    variant: 5,
    trigger: "on_screen_load",
    text: "वाह! सब तैयार अछि।",
    romanTransliteration: "Vaah! Sab taiyaar achhi.",
    englishMeaning: "Wow! Everything is ready.",
    language: "hi-IN",
    speaker: "priya",
    pace: 0.95,
    pauseAfterMs: 800,
    maxDurationS: 6,
    emotionalTone: "celebratory",
    fallback: true,
  },

  // ==================== SANSKRIT (hi-IN fallback) ====================
  {
    screenId: "S-0.0.6",
    variant: 1,
    trigger: "on_screen_load",
    text: "अतिशय उत्तमम्! सेटअप पूर्णम्।",
    romanTransliteration: "Atishaya uttamam! Setup poornam.",
    englishMeaning: "Excellent! Setup complete.",
    language: "hi-IN",
    speaker: "priya",
    pace: 0.90,
    pauseAfterMs: 800,
    maxDurationS: 6,
    emotionalTone: "celebratory",
    fallback: true,
  },
  {
    screenId: "S-0.0.6",
    variant: 2,
    trigger: "on_screen_load",
    text: "साधु! भवान् सज्जः अस्ति।",
    romanTransliteration: "Saadhu! Bhavaan sajjah asti.",
    englishMeaning: "Well done! You are ready.",
    language: "hi-IN",
    speaker: "priya",
    pace: 0.90,
    pauseAfterMs: 800,
    maxDurationS: 6,
    emotionalTone: "celebratory",
    fallback: true,
  },
  {
    screenId: "S-0.0.6",
    variant: 3,
    trigger: "on_screen_load",
    text: "धन्यवादः! स्वागतम्।",
    romanTransliteration: "Dhanyavaadah! Swaagatham.",
    englishMeaning: "Thank you! Welcome.",
    language: "hi-IN",
    speaker: "priya",
    pace: 0.89,
    pauseAfterMs: 800,
    maxDurationS: 6,
    emotionalTone: "celebratory",
    fallback: true,
  },
  {
    screenId: "S-0.0.6",
    variant: 4,
    trigger: "on_screen_load",
    text: "सफलता! इदानीं आरभामहे।",
    romanTransliteration: "Safalta! Idaaneem aarbhaamahe.",
    englishMeaning: "Success! Now let's begin.",
    language: "hi-IN",
    speaker: "priya",
    pace: 0.91,
    pauseAfterMs: 800,
    maxDurationS: 6,
    emotionalTone: "celebratory",
    fallback: true,
  },
  {
    screenId: "S-0.0.6",
    variant: 5,
    trigger: "on_screen_load",
    text: "आश्चर्यम्! सर्वं सज्जम्।",
    romanTransliteration: "Aashcharyam! Sarvam sajjam.",
    englishMeaning: "Wow! Everything is ready.",
    language: "hi-IN",
    speaker: "priya",
    pace: 0.92,
    pauseAfterMs: 800,
    maxDurationS: 6,
    emotionalTone: "celebratory",
    fallback: true,
  },

  // ==================== ASSAMESE (hi-IN fallback) ====================
  {
    screenId: "S-0.0.6",
    variant: 1,
    trigger: "on_screen_load",
    text: "অতি ভাল! চেটআপ সম্পূৰ্ণ হ'ল।",
    romanTransliteration: "Ati bhal! Setup sompurno hol.",
    englishMeaning: "Excellent! Setup complete.",
    language: "hi-IN",
    speaker: "priya",
    pace: 0.92,
    pauseAfterMs: 800,
    maxDurationS: 6,
    emotionalTone: "celebratory",
    fallback: true,
  },
  {
    screenId: "S-0.0.6",
    variant: 2,
    trigger: "on_screen_load",
    text: "বাহ! আপুনি সাজু।",
    romanTransliteration: "Baa! Apuni saaju.",
    englishMeaning: "Well done! You are ready.",
    language: "hi-IN",
    speaker: "priya",
    pace: 0.92,
    pauseAfterMs: 800,
    maxDurationS: 6,
    emotionalTone: "celebratory",
    fallback: true,
  },
  {
    screenId: "S-0.0.6",
    variant: 3,
    trigger: "on_screen_load",
    text: "ধন্যবাদ! আদৰণি।",
    romanTransliteration: "Dhonnobad! Adoroni.",
    englishMeaning: "Thank you! Welcome.",
    language: "hi-IN",
    speaker: "priya",
    pace: 0.91,
    pauseAfterMs: 800,
    maxDurationS: 6,
    emotionalTone: "celebratory",
    fallback: true,
  },
  {
    screenId: "S-0.0.6",
    variant: 4,
    trigger: "on_screen_load",
    text: "সফল! এতিয়া আৰম্ভ কৰোঁ।",
    romanTransliteration: "Sofol! Etiya arambho koro.",
    englishMeaning: "Success! Now let's begin.",
    language: "hi-IN",
    speaker: "priya",
    pace: 0.93,
    pauseAfterMs: 800,
    maxDurationS: 6,
    emotionalTone: "celebratory",
    fallback: true,
  },
  {
    screenId: "S-0.0.6",
    variant: 5,
    trigger: "on_screen_load",
    text: "বাঃ! সকলো সাজু।",
    romanTransliteration: "Baa! Sokolo saaju.",
    englishMeaning: "Wow! Everything is ready.",
    language: "hi-IN",
    speaker: "priya",
    pace: 0.94,
    pauseAfterMs: 800,
    maxDurationS: 6,
    emotionalTone: "celebratory",
    fallback: true,
  },
];

export default S0_0_6_CELEBRATION;
