/**
 * S-0.0.8: Error/Retry Screen Scripts
 * Screen: Show error message and retry option
 * Total: 45 scripts (15 languages × 3 variants)
 */

export const S0_0_8_ERROR_RETRY = [
  // ==================== HINDI (hi-IN) ====================
  {
    screenId: "S-0.0.8",
    variant: 1,
    trigger: "on_screen_load",
    text: "कुछ गलत हुआ। पुनः प्रयास करें।",
    romanTransliteration: "Kuch galat hua. Punah prayaas karein.",
    englishMeaning: "Something went wrong. Please try again.",
    language: "hi-IN",
    speaker: "priya",
    pace: 0.85,
    pauseAfterMs: 1100,
    maxDurationS: 7,
    emotionalTone: "reassuring",
  },
  {
    screenId: "S-0.0.8",
    variant: 2,
    trigger: "on_screen_load",
    text: "त्रुटि हुई। फिर से कोशिश करें।",
    romanTransliteration: "Truti hui. Fir se koshish karein.",
    englishMeaning: "Error occurred. Try again.",
    language: "hi-IN",
    speaker: "priya",
    pace: 0.85,
    pauseAfterMs: 1100,
    maxDurationS: 7,
    emotionalTone: "reassuring",
  },
  {
    screenId: "S-0.0.8",
    variant: 3,
    trigger: "on_screen_load",
    text: "समस्या आई। दोबारा प्रयास करें।",
    romanTransliteration: "Samasya aayi. Dobara prayaas karein.",
    englishMeaning: "Problem occurred. Try again.",
    language: "hi-IN",
    speaker: "priya",
    pace: 0.87,
    pauseAfterMs: 1100,
    maxDurationS: 7,
    emotionalTone: "reassuring",
  },

  // ==================== TAMIL (ta-IN) ====================
  {
    screenId: "S-0.0.8",
    variant: 1,
    trigger: "on_screen_load",
    text: "ஏதோ தவறு நடந்தது. மீண்டும் முயற்சிக்கவும்.",
    romanTransliteration: "Yetho thavaru nadandhadhu. Meendum muyarchikkavum.",
    englishMeaning: "Something went wrong. Please try again.",
    language: "ta-IN",
    speaker: "priya",
    pace: 0.83,
    pauseAfterMs: 1100,
    maxDurationS: 7,
    emotionalTone: "reassuring",
  },
  {
    screenId: "S-0.0.8",
    variant: 2,
    trigger: "on_screen_load",
    text: "பிழை ஏற்பட்டது. மீண்டும் முயற்சிக்கவும்.",
    romanTransliteration: "Pizhai yerpattadhu. Meendum muyarchikkavum.",
    englishMeaning: "Error occurred. Try again.",
    language: "ta-IN",
    speaker: "priya",
    pace: 0.83,
    pauseAfterMs: 1100,
    maxDurationS: 7,
    emotionalTone: "reassuring",
  },
  {
    screenId: "S-0.0.8",
    variant: 3,
    trigger: "on_screen_load",
    text: "சிக்கல் வந்தது. மீண்டும் செய்யவும்.",
    romanTransliteration: "Sikkal vandhadhu. Meendum seyyavum.",
    englishMeaning: "Problem occurred. Try again.",
    language: "ta-IN",
    speaker: "priya",
    pace: 0.85,
    pauseAfterMs: 1100,
    maxDurationS: 7,
    emotionalTone: "reassuring",
  },

  // ==================== TELUGU (te-IN) ====================
  {
    screenId: "S-0.0.8",
    variant: 1,
    trigger: "on_screen_load",
    text: "ఏదో తప్పు జరిగింది. మళ్లీ ప్రయత్నించండి.",
    romanTransliteration: "Yedo thappu jarigindi. Malli prayatninchandi.",
    englishMeaning: "Something went wrong. Please try again.",
    language: "te-IN",
    speaker: "priya",
    pace: 0.84,
    pauseAfterMs: 1100,
    maxDurationS: 7,
    emotionalTone: "reassuring",
  },
  {
    screenId: "S-0.0.8",
    variant: 2,
    trigger: "on_screen_load",
    text: "లోపం సంభవించింది. మళ్లీ ప్రయత్నించండి.",
    romanTransliteration: "Lopam sambhavinchindi. Malli prayatninchandi.",
    englishMeaning: "Error occurred. Try again.",
    language: "te-IN",
    speaker: "priya",
    pace: 0.84,
    pauseAfterMs: 1100,
    maxDurationS: 7,
    emotionalTone: "reassuring",
  },
  {
    screenId: "S-0.0.8",
    variant: 3,
    trigger: "on_screen_load",
    text: "సమస్య వచ్చింది. మళ్లీ చేయండి.",
    romanTransliteration: "Samasya vachchindi. Malli cheyandi.",
    englishMeaning: "Problem occurred. Try again.",
    language: "te-IN",
    speaker: "priya",
    pace: 0.86,
    pauseAfterMs: 1100,
    maxDurationS: 7,
    emotionalTone: "reassuring",
  },

  // ==================== BENGALI (bn-IN) ====================
  {
    screenId: "S-0.0.8",
    variant: 1,
    trigger: "on_screen_load",
    text: "কিছু ভুল হয়েছে। আবার চেষ্টা করুন।",
    romanTransliteration: "Kichu bhul hoyeche. Abar cheshta korun.",
    englishMeaning: "Something went wrong. Please try again.",
    language: "bn-IN",
    speaker: "priya",
    pace: 0.85,
    pauseAfterMs: 1100,
    maxDurationS: 7,
    emotionalTone: "reassuring",
  },
  {
    screenId: "S-0.0.8",
    variant: 2,
    trigger: "on_screen_load",
    text: "ত্রুটি হয়েছে। আবার চেষ্টা করুন।",
    romanTransliteration: "Truti hoyeche. Abar cheshta korun.",
    englishMeaning: "Error occurred. Try again.",
    language: "bn-IN",
    speaker: "priya",
    pace: 0.85,
    pauseAfterMs: 1100,
    maxDurationS: 7,
    emotionalTone: "reassuring",
  },
  {
    screenId: "S-0.0.8",
    variant: 3,
    trigger: "on_screen_load",
    text: "সমস্যা হয়েছে। পুনরায় চেষ্টা করুন।",
    romanTransliteration: "Shomoshya hoyeche. Punoray cheshta korun.",
    englishMeaning: "Problem occurred. Try again.",
    language: "bn-IN",
    speaker: "priya",
    pace: 0.87,
    pauseAfterMs: 1100,
    maxDurationS: 7,
    emotionalTone: "reassuring",
  },

  // ==================== MARATHI (mr-IN) ====================
  {
    screenId: "S-0.0.8",
    variant: 1,
    trigger: "on_screen_load",
    text: "काहीतरी चुकले. पुन्हा प्रयत्न करा.",
    romanTransliteration: "Kahitari chukle. Punha prayatna kara.",
    englishMeaning: "Something went wrong. Please try again.",
    language: "mr-IN",
    speaker: "priya",
    pace: 0.86,
    pauseAfterMs: 1100,
    maxDurationS: 7,
    emotionalTone: "reassuring",
  },
  {
    screenId: "S-0.0.8",
    variant: 2,
    trigger: "on_screen_load",
    text: "त्रुटी झाली. पुन्हा प्रयत्न करा.",
    romanTransliteration: "Truti zhaali. Punha prayatna kara.",
    englishMeaning: "Error occurred. Try again.",
    language: "mr-IN",
    speaker: "priya",
    pace: 0.86,
    pauseAfterMs: 1100,
    maxDurationS: 7,
    emotionalTone: "reassuring",
  },
  {
    screenId: "S-0.0.8",
    variant: 3,
    trigger: "on_screen_load",
    text: "अडचण आली. पुन्हा करा.",
    romanTransliteration: "Adarchan aali. Punha kara.",
    englishMeaning: "Problem occurred. Try again.",
    language: "mr-IN",
    speaker: "priya",
    pace: 0.88,
    pauseAfterMs: 1100,
    maxDurationS: 7,
    emotionalTone: "reassuring",
  },

  // ==================== GUJARATI (gu-IN) ====================
  {
    screenId: "S-0.0.8",
    variant: 1,
    trigger: "on_screen_load",
    text: "કંઈક ખોટું થયું. પુનઃ પ્રયાસ કરો.",
    romanTransliteration: "Kankik khotu thayu. Punah prayas karo.",
    englishMeaning: "Something went wrong. Please try again.",
    language: "gu-IN",
    speaker: "priya",
    pace: 0.85,
    pauseAfterMs: 1100,
    maxDurationS: 7,
    emotionalTone: "reassuring",
  },
  {
    screenId: "S-0.0.8",
    variant: 2,
    trigger: "on_screen_load",
    text: "ભૂલ થઈ. પુનઃ પ્રયાસ કરો.",
    romanTransliteration: "Bhul thai. Punah prayas karo.",
    englishMeaning: "Error occurred. Try again.",
    language: "gu-IN",
    speaker: "priya",
    pace: 0.85,
    pauseAfterMs: 1100,
    maxDurationS: 7,
    emotionalTone: "reassuring",
  },
  {
    screenId: "S-0.0.8",
    variant: 3,
    trigger: "on_screen_load",
    text: "સમસ્યા આવી. ફરીથી પ્રયાસ કરો.",
    romanTransliteration: "Samasya aavi. Farithi prayas karo.",
    englishMeaning: "Problem occurred. Try again.",
    language: "gu-IN",
    speaker: "priya",
    pace: 0.87,
    pauseAfterMs: 1100,
    maxDurationS: 7,
    emotionalTone: "reassuring",
  },

  // ==================== KANNADA (kn-IN) ====================
  {
    screenId: "S-0.0.8",
    variant: 1,
    trigger: "on_screen_load",
    text: "ಏನೋ ತಪ್ಪಾಗಿದೆ. ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.",
    romanTransliteration: "Yeno thappaagide. Matte prayatnisi.",
    englishMeaning: "Something went wrong. Please try again.",
    language: "kn-IN",
    speaker: "priya",
    pace: 0.84,
    pauseAfterMs: 1100,
    maxDurationS: 7,
    emotionalTone: "reassuring",
  },
  {
    screenId: "S-0.0.8",
    variant: 2,
    trigger: "on_screen_load",
    text: "ದೋಷ ಸಂಭವಿಸಿದೆ. ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.",
    romanTransliteration: "Dosha sambhavishide. Matte prayatnisi.",
    englishMeaning: "Error occurred. Try again.",
    language: "kn-IN",
    speaker: "priya",
    pace: 0.84,
    pauseAfterMs: 1100,
    maxDurationS: 7,
    emotionalTone: "reassuring",
  },
  {
    screenId: "S-0.0.8",
    variant: 3,
    trigger: "on_screen_load",
    text: "ಸಮಸ್ಯೆ ಬಂದಿದೆ. ಮತ್ತೆ ಮಾಡಿ.",
    romanTransliteration: "Samasye bandide. Matte maadi.",
    englishMeaning: "Problem occurred. Try again.",
    language: "kn-IN",
    speaker: "priya",
    pace: 0.86,
    pauseAfterMs: 1100,
    maxDurationS: 7,
    emotionalTone: "reassuring",
  },

  // ==================== MALAYALAM (ml-IN) ====================
  {
    screenId: "S-0.0.8",
    variant: 1,
    trigger: "on_screen_load",
    text: "എന്തോ തെറ്റിപ്പോയി. വീണ്ടും ശ്രമിക്കുക.",
    romanTransliteration: "Entho thettippoyi. Veendum shramikkuka.",
    englishMeaning: "Something went wrong. Please try again.",
    language: "ml-IN",
    speaker: "priya",
    pace: 0.83,
    pauseAfterMs: 1100,
    maxDurationS: 7,
    emotionalTone: "reassuring",
  },
  {
    screenId: "S-0.0.8",
    variant: 2,
    trigger: "on_screen_load",
    text: "പിശകുണ്ടായി. വീണ്ടും ശ്രമിക്കുക.",
    romanTransliteration: "Pishakundayi. Veendum shramikkuka.",
    englishMeaning: "Error occurred. Try again.",
    language: "ml-IN",
    speaker: "priya",
    pace: 0.83,
    pauseAfterMs: 1100,
    maxDurationS: 7,
    emotionalTone: "reassuring",
  },
  {
    screenId: "S-0.0.8",
    variant: 3,
    trigger: "on_screen_load",
    text: "പ്രശ്നം വന്നു. വീണ്ടും ചെയ്യുക.",
    romanTransliteration: "Prashnam vannu. Veendum cheyyuka.",
    englishMeaning: "Problem occurred. Try again.",
    language: "ml-IN",
    speaker: "priya",
    pace: 0.85,
    pauseAfterMs: 1100,
    maxDurationS: 7,
    emotionalTone: "reassuring",
  },

  // ==================== PUNJABI (pa-IN) ====================
  {
    screenId: "S-0.0.8",
    variant: 1,
    trigger: "on_screen_load",
    text: "ਕੁਝ ਗਲਤ ਹੋਇਆ। ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ।",
    romanTransliteration: "Kujh galat hoya. Dubara koshish karo.",
    englishMeaning: "Something went wrong. Please try again.",
    language: "pa-IN",
    speaker: "priya",
    pace: 0.85,
    pauseAfterMs: 1100,
    maxDurationS: 7,
    emotionalTone: "reassuring",
  },
  {
    screenId: "S-0.0.8",
    variant: 2,
    trigger: "on_screen_load",
    text: "ਗਲਤੀ ਹੋਈ। ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ।",
    romanTransliteration: "Galati hoi. Dubara koshish karo.",
    englishMeaning: "Error occurred. Try again.",
    language: "pa-IN",
    speaker: "priya",
    pace: 0.85,
    pauseAfterMs: 1100,
    maxDurationS: 7,
    emotionalTone: "reassuring",
  },
  {
    screenId: "S-0.0.8",
    variant: 3,
    trigger: "on_screen_load",
    text: "ਸਮੱਸਿਆ ਆਈ। ਮੁੜ ਕੋਸ਼ਿਸ਼ ਕਰੋ।",
    romanTransliteration: "Samasya aayi. Mud koshish karo.",
    englishMeaning: "Problem occurred. Try again.",
    language: "pa-IN",
    speaker: "priya",
    pace: 0.87,
    pauseAfterMs: 1100,
    maxDurationS: 7,
    emotionalTone: "reassuring",
  },

  // ==================== ODIA (or-IN) ====================
  {
    screenId: "S-0.0.8",
    variant: 1,
    trigger: "on_screen_load",
    text: "କିଛି ଭୁଲ ହେଲା। ପୁନର୍ବାର ଚେଷ୍ଟା କରନ୍ତୁ।",
    romanTransliteration: "Kichi bhula hela. Punarbara chesta karantu.",
    englishMeaning: "Something went wrong. Please try again.",
    language: "or-IN",
    speaker: "priya",
    pace: 0.84,
    pauseAfterMs: 1100,
    maxDurationS: 7,
    emotionalTone: "reassuring",
  },
  {
    screenId: "S-0.0.8",
    variant: 2,
    trigger: "on_screen_load",
    text: "ତ୍ରୁଟି ହେଲା। ପୁନର୍ବାର ଚେଷ୍ଟା କରନ୍ତୁ।",
    romanTransliteration: "Truti hela. Punarbara chesta karantu.",
    englishMeaning: "Error occurred. Try again.",
    language: "or-IN",
    speaker: "priya",
    pace: 0.84,
    pauseAfterMs: 1100,
    maxDurationS: 7,
    emotionalTone: "reassuring",
  },
  {
    screenId: "S-0.0.8",
    variant: 3,
    trigger: "on_screen_load",
    text: "ସମସ୍ୟା ଆସିଲା। ପୁନର୍ବାର କରନ୍ତୁ।",
    romanTransliteration: "Samasya asila. Punarbara karantu.",
    englishMeaning: "Problem occurred. Try again.",
    language: "or-IN",
    speaker: "priya",
    pace: 0.86,
    pauseAfterMs: 1100,
    maxDurationS: 7,
    emotionalTone: "reassuring",
  },

  // ==================== ENGLISH (en-IN) ====================
  {
    screenId: "S-0.0.8",
    variant: 1,
    trigger: "on_screen_load",
    text: "Something went wrong. Try again.",
    romanTransliteration: "Something went wrong. Try again.",
    englishMeaning: "Something went wrong. Try again.",
    language: "en-IN",
    speaker: "priya",
    pace: 0.87,
    pauseAfterMs: 1100,
    maxDurationS: 7,
    emotionalTone: "reassuring",
  },
  {
    screenId: "S-0.0.8",
    variant: 2,
    trigger: "on_screen_load",
    text: "An error occurred. Please retry.",
    romanTransliteration: "An error occurred. Please retry.",
    englishMeaning: "An error occurred. Please retry.",
    language: "en-IN",
    speaker: "priya",
    pace: 0.87,
    pauseAfterMs: 1100,
    maxDurationS: 7,
    emotionalTone: "reassuring",
  },
  {
    screenId: "S-0.0.8",
    variant: 3,
    trigger: "on_screen_load",
    text: "There was a problem. Try again.",
    romanTransliteration: "There was a problem. Try again.",
    englishMeaning: "There was a problem. Try again.",
    language: "en-IN",
    speaker: "priya",
    pace: 0.89,
    pauseAfterMs: 1100,
    maxDurationS: 7,
    emotionalTone: "reassuring",
  },

  // ==================== BHOJPURI (hi-IN fallback) ====================
  {
    screenId: "S-0.0.8",
    variant: 1,
    trigger: "on_screen_load",
    text: "कुछ गलत भइल। फेर से कोसिस करीं।",
    romanTransliteration: "Kuch galat bhail. Fer se kosis kareen.",
    englishMeaning: "Something went wrong. Please try again.",
    language: "hi-IN",
    speaker: "priya",
    pace: 0.85,
    pauseAfterMs: 1100,
    maxDurationS: 7,
    emotionalTone: "reassuring",
    fallback: true,
  },
  {
    screenId: "S-0.0.8",
    variant: 2,
    trigger: "on_screen_load",
    text: "गलती भइल। पुनः प्रयास करीं।",
    romanTransliteration: "Galati bhail. Punah prayaas kareen.",
    englishMeaning: "Error occurred. Try again.",
    language: "hi-IN",
    speaker: "priya",
    pace: 0.85,
    pauseAfterMs: 1100,
    maxDurationS: 7,
    emotionalTone: "reassuring",
    fallback: true,
  },
  {
    screenId: "S-0.0.8",
    variant: 3,
    trigger: "on_screen_load",
    text: "समस्या भइल। दोबारा कोसिस करीं।",
    romanTransliteration: "Samasya bhail. Dobara kosis kareen.",
    englishMeaning: "Problem occurred. Try again.",
    language: "hi-IN",
    speaker: "priya",
    pace: 0.87,
    pauseAfterMs: 1100,
    maxDurationS: 7,
    emotionalTone: "reassuring",
    fallback: true,
  },

  // ==================== MAITHILI (hi-IN fallback) ====================
  {
    screenId: "S-0.0.8",
    variant: 1,
    trigger: "on_screen_load",
    text: "किछु गलत भेल। फेर सँ कोशिश करू।",
    romanTransliteration: "Kichu galat bhel. Fer san koshish karu.",
    englishMeaning: "Something went wrong. Please try again.",
    language: "hi-IN",
    speaker: "priya",
    pace: 0.85,
    pauseAfterMs: 1100,
    maxDurationS: 7,
    emotionalTone: "reassuring",
    fallback: true,
  },
  {
    screenId: "S-0.0.8",
    variant: 2,
    trigger: "on_screen_load",
    text: "त्रुटि भेल। पुनः प्रयास करू।",
    romanTransliteration: "Truti bhel. Punah prayaas karu.",
    englishMeaning: "Error occurred. Try again.",
    language: "hi-IN",
    speaker: "priya",
    pace: 0.85,
    pauseAfterMs: 1100,
    maxDurationS: 7,
    emotionalTone: "reassuring",
    fallback: true,
  },
  {
    screenId: "S-0.0.8",
    variant: 3,
    trigger: "on_screen_load",
    text: "समस्या भेल। दोबारा कोशिश करू।",
    romanTransliteration: "Samasya bhel. Dobara koshish karu.",
    englishMeaning: "Problem occurred. Try again.",
    language: "hi-IN",
    speaker: "priya",
    pace: 0.87,
    pauseAfterMs: 1100,
    maxDurationS: 7,
    emotionalTone: "reassuring",
    fallback: true,
  },

  // ==================== SANSKRIT (hi-IN fallback) ====================
  {
    screenId: "S-0.0.8",
    variant: 1,
    trigger: "on_screen_load",
    text: "किमपि त्रुटम् अभवत्। पुनः यतस्व।",
    romanTransliteration: "Kimapi trutam abhavat. Punah yatasva.",
    englishMeaning: "Something went wrong. Try again.",
    language: "hi-IN",
    speaker: "priya",
    pace: 0.82,
    pauseAfterMs: 1100,
    maxDurationS: 7,
    emotionalTone: "reassuring",
    fallback: true,
  },
  {
    screenId: "S-0.0.8",
    variant: 2,
    trigger: "on_screen_load",
    text: "दोषः जातः। पुनः प्रयतस्व।",
    romanTransliteration: "Doshah jaatah. Punah prayatasva.",
    englishMeaning: "Error occurred. Try again.",
    language: "hi-IN",
    speaker: "priya",
    pace: 0.82,
    pauseAfterMs: 1100,
    maxDurationS: 7,
    emotionalTone: "reassuring",
    fallback: true,
  },
  {
    screenId: "S-0.0.8",
    variant: 3,
    trigger: "on_screen_load",
    text: "समस्या अभवत्। भूयः यतस्व।",
    romanTransliteration: "Samasya abhavat. Bhuyah yatasva.",
    englishMeaning: "Problem occurred. Try again.",
    language: "hi-IN",
    speaker: "priya",
    pace: 0.84,
    pauseAfterMs: 1100,
    maxDurationS: 7,
    emotionalTone: "reassuring",
    fallback: true,
  },

  // ==================== ASSAMESE (hi-IN fallback) ====================
  {
    screenId: "S-0.0.8",
    variant: 1,
    trigger: "on_screen_load",
    text: "কিবা এটা ভুল হ'ল। পুনৰ চেষ্টা কৰক।",
    romanTransliteration: "Kiba eta bhul hol. Punor chesta korok.",
    englishMeaning: "Something went wrong. Please try again.",
    language: "hi-IN",
    speaker: "priya",
    pace: 0.84,
    pauseAfterMs: 1100,
    maxDurationS: 7,
    emotionalTone: "reassuring",
    fallback: true,
  },
  {
    screenId: "S-0.0.8",
    variant: 2,
    trigger: "on_screen_load",
    text: "ভুল হ'ল। পুনৰ চেষ্টা কৰক।",
    romanTransliteration: "Bhul hol. Punor chesta korok.",
    englishMeaning: "Error occurred. Try again.",
    language: "hi-IN",
    speaker: "priya",
    pace: 0.84,
    pauseAfterMs: 1100,
    maxDurationS: 7,
    emotionalTone: "reassuring",
    fallback: true,
  },
  {
    screenId: "S-0.0.8",
    variant: 3,
    trigger: "on_screen_load",
    text: "সমস্যা হ'ল। পুনৰ চেষ্টা কৰক।",
    romanTransliteration: "Shomoshya hol. Punor chesta korok.",
    englishMeaning: "Problem occurred. Try again.",
    language: "hi-IN",
    speaker: "priya",
    pace: 0.86,
    pauseAfterMs: 1100,
    maxDurationS: 7,
    emotionalTone: "reassuring",
    fallback: true,
  },
];

export default S0_0_8_ERROR_RETRY;
